"""Narration + scenes for:
"The AI Bubble in Europe: I Replayed the Dot-Com Crash on Your World ETF"

Each S(...) is one narration segment and the scene shown while it is spoken.
Tokens starting with '@' in the narration are reveal markers: an element with
at='x' appears when the narrator reaches the word that follows '@x'.
Visual markup: {a:text} amber, {r:text} red, {g:text} green, {m:text} muted.
"""
from data import MSCI_WORLD_EUR, EURO_GOV_BONDS, lump_sum_path, mix, monthly_plan

# ---------------------------------------------------------------- datasets
X = [1999] + list(range(2000, 2026)) + [2026 + 8 / 12]
WORLD = lump_sum_path(MSCI_WORLD_EUR)
SIXTY40 = lump_sum_path(mix(MSCI_WORLD_EUR, EURO_GOV_BONDS, 0.6))
PLAN = monthly_plan(MSCI_WORLD_EUR, start=2000)
PLAN_X = [1999] + [p[0] if p[0] < 2026 else 2026 + 8 / 12 for p in PLAN]
PLAN_V = [0] + [p[1] for p in PLAN]
PLAN_PAID = [0] + [p[2] for p in PLAN]

SRC_WORLD = "MSCI World, net, in EUR, after 0.2% fees · year-end values · 2026 = end of August"
SRC_ECB = "ECB Blog, “The AI boom: rational enthusiasm or the next dot-com bubble?”, Aug 2026"


def S(narration, *elements, src=None, chapter=None):
    return dict(text=narration, elements=list(elements), src=src, chapter=chapter)


def E(kind, **kw):
    kw["kind"] = kind
    return kw


def pill(t, **k): return E("pill", text=t, **k)
def tag(t, color="muted", **k): return E("tag", text=t, color=color, **k)
def head(t, size=72, **k): return E("head", text=t, size=size, **k)
def sub(t, size=44, **k): return E("sub", text=t, size=size, **k)
def big(t, color="amber", size=190, **k): return E("big", text=t, color=color, size=size, **k)
def count(to, fmt, color="amber", size=190, frm=0, **k):
    return E("big", text=None, to=to, frm=frm, fmt=fmt, color=color, size=size, **k)
def gap(h=30): return E("gap", h=h)
def chips(items, **k): return E("chips", items=items, **k)
def rows(items, **k): return E("rows", items=items, **k)
def bars(items, maxv=None, **k): return E("bars", items=items, maxv=maxv, **k)
def options(items, correct=None, reveal=None, countdown=True, **k):
    return E("options", items=items, correct=correct, reveal=reveal, countdown=countdown, **k)
def waffle(groups, **k): return E("waffle", groups=groups, **k)
def strike(t, stamp, **k): return E("strike", text=t, stamp=stamp, **k)
def boxes(items, note="comment below", **k): return E("boxes", items=items, note=note, **k)
def table(header, items, **k): return E("table", header=header, items=items, **k)
def chart(series, **k): return E("chart", series=series, **k)
def card(label, title, **k): return E("card", label=label, title=title, **k)


def world_series(upto, frm=None, color="amber", end_label=True, data=None):
    return dict(x=X, y=data or WORLD, upto=upto, frm=frm, color=color, end_label=end_label)


WORLD_AXES = dict(xr=(1999, 2027), yr=(0, 50000), xticks=[2000, 2005, 2010, 2015, 2020, 2025],
                  yticks=[(10000, "€10k"), (25000, "€25k"), (50000, "€50k")], ref=10000)
CRASH_AXES = dict(xr=(1999, 2014), yr=(4000, 11000), xticks=[2000, 2004, 2008, 2012],
                  yticks=[(5000, "€5k"), (10000, "€10k")], ref=10000)

CH = ["What you really own", "We've been here before", "The replay",
      "The currency trap", "The stress test", "What actually protected you",
      "The number that matters"]


def chapter(i):
    return [tag(f"CHAPTER {i}/7", color="amber"), head(CH[i - 1], size=96)]


SEGMENTS = [
    # ================================================================ COLD OPEN
    S("@a Four hundred and forty billion euros.",
      count(440, "€{:,.0f} BILLION", size=170, at="a"),
      src=SRC_ECB),
    S("That's how much households in Europe hold in American tech stocks, according to economists at the European Central Bank.",
      count(440, "€{:,.0f} BILLION", size=170, frm=440),
      sub("held by EU households in {a:US tech stocks}"),
      src=SRC_ECB),
    S("And here's the part that got my attention: @a most of them don't even know it.",
      count(440, "€{:,.0f} BILLION", size=170, frm=440),
      sub("held by EU households in {a:US tech stocks}"),
      head("…and most {r:don't know it}", size=64, at="a"),
      src=SRC_ECB),
    S("And it's not just households. According to the same analysis, insurance companies and pension funds have a similar exposure to big tech. @a So even your pension may be making the same bet.",
      head("Insurers. Pension funds."),
      sub("Even your pension may be making {a:the same bet}.", at="a"),
      src=SRC_ECB),
    S("Because they never bought Nvidia. They never bought Microsoft. @a They bought a world ETF.",
      chips(["Nvidia", "Microsoft"], strike=True),
      head("They bought a {a:world ETF}.", at="a")),
    S("One fund. Thousands of companies. @a Safe, simple, diversified. At least, that's the idea.",
      head("One fund. {a:Thousands of companies.}"),
      sub("Safe. Simple. Diversified.", at="a")),
    S("Now look at what happened in September. In the middle of the month, the Nasdaq one hundred lost more than @a six hundred billion dollars in two days.",
      tag("SEPTEMBER 2026"),
      head("Nasdaq-100, two days"),
      count(-600, "−${:,.0f}B", color="red", frm=0, at="a"),
      src="Nasdaq-100 market value, 14–15 Sep 2026"),
    S("Then, within a week, @a it bounced back by trillions. Fear, then greed, then fear again.",
      tag("SEPTEMBER 2026"),
      head("…then, within a week"),
      big("+$3T", color="green", at="a"),
      src="Nasdaq-100 market value added from the 15 Sep low"),
    S("Valuations in the US are at the @a second highest level in more than a hundred and fifty years.",
      tag("S&P 500 · SHILLER CAPE"),
      big("41", color="amber", at="a"),
      sub("2nd highest in 150+ years"),
      src="Shiller CAPE, September 2026"),
    S("The only time they were higher? @a December 1999.",
      tag("S&P 500 · SHILLER CAPE"),
      rows([("Today", "41", "amber"), ("Dec 1999", "44", "red")], at="a"),
      src="Shiller CAPE: 44.2 in Dec 1999, ~41 in Sep 2026"),
    S("So I did what this channel does. I took real euro data, going back to 1999, @a and I replayed the dot-com crash on the portfolio most Europeans own today.",
      head("So I {a:tested} it."),
      sub("Real euro data · 1999 → 2026", at="a")),
    S("You'll see how long it took to get your money back, what the dollar did to euro investors, @a which safer alternatives actually helped, and which ones barely made a difference.",
      rows([("Time to get your money back", "?", "amber"), ("What the dollar did", "?", "amber"),
            ("Which alternatives helped", "?", "amber")])),
    S("And at the end, I'll show you one number that matters more than any crash.",
      head("One number that matters {a:more than any crash}.")),
    S("This is The AI Bubble in Europe.",
      head("THE AI BUBBLE {a:IN EUROPE}", size=110),
      sub("I replayed the dot-com crash on your world ETF")),

    # ================================================================ CHAPTER 1
    S("Chapter one. What you really own.", *chapter(1)),
    S("The most popular index for European ETF investors is the M S C I World. It holds @a over thirteen hundred companies, @b in twenty-three developed countries.",
      tag("MSCI WORLD"),
      count(1300, "{:,.0f}+", size=170, at="a"),
      sub("companies in {a:23 countries}", at="b")),
    S("Together with its bigger cousins, the All-World and A C W I funds, it sits behind millions of savings plans, from Germany to Spain, from France to the Netherlands.",
      tag("MSCI WORLD"),
      head("Behind {a:millions} of savings plans"),
      sub("Germany · Spain · France · Netherlands · Italy")),
    S("European ETFs now hold a record @a three point nine seven trillion dollars. @b And this year alone, investors added three hundred and eighty one billion more.",
      tag("EUROPEAN ETF MARKET · AUGUST 2026"),
      count(3.97, "${:.2f}T", color="amber", size=170, at="a"),
      sub("+{g:$381B} of net inflows this year", at="b"),
      src="ETFGI, European ETF industry, end of August 2026"),
    S("Most of that money flows into the same handful of global index funds. So what's actually inside them matters to a lot of people.",
      head("Same funds. {a:Same exposure.}")),
    S("That sounds diversified. But the index is weighted by size. The bigger a company, the more of your money goes into it.",
      tag("MSCI WORLD"),
      head("Weighted by {a:size}."),
      sub("Bigger company → more of your money")),
    S("So let's follow one hundred euros into a world ETF today. Every square is one euro.",
      tag("€100 INTO A WORLD ETF"),
      waffle([(100, "slate", "")])),
    S("More than @a seventy of them go to American companies.",
      tag("€100 INTO A WORLD ETF"),
      waffle([(71, "amber", "USA"), (29, "slate", "Rest of the world")], at="a"),
      src="MSCI World country weights, end of August 2026"),
    S("And about @a twenty-seven euros go to just ten companies.",
      tag("€100 INTO A WORLD ETF"),
      waffle([(27, "red", "Top 10 companies"), (44, "amber", "Rest of USA"), (29, "slate", "Rest of the world")], at="a"),
      src="MSCI World top-10 weight ≈ 27%, August 2026"),
    S("Put differently: if those ten companies fell by half tomorrow, @a your whole world ETF would lose about thirteen percent, even if every other company on Earth stood perfectly still.",
      tag("IF THE TOP 10 FELL 50%"),
      count(-13.5, "{:.1f}%", color="red", frm=0, at="a"),
      sub("…with every other company {a:unchanged}")),
    S("Who are they? @a Nvidia, Microsoft, Apple, Broadcom, Amazon, Alphabet, Meta. The names behind almost every AI headline.",
      tag("THE GIANTS"),
      chips(["Nvidia", "Microsoft", "Apple", "Broadcom", "Amazon", "Alphabet", "Meta"], at="a")),
    S("Nvidia alone is valued at around @a five point three trillion dollars. That's more than every listed company in Germany put together.",
      tag("NVIDIA"),
      big("$5.3T", color="amber", at="a"),
      sub("more than the whole German stock market")),
    S("And this concentration is new. Not long ago, the five biggest companies were around @a six percent of the world index. @b By the end of 2024, they were close to twenty percent.",
      tag("TOP 5 WEIGHT IN MSCI WORLD"),
      bars([("Before", 6, "6%", "slate"), ("End of 2024", 20, "≈20%", "red")], maxv=22, at="a"),
      src="MSCI World, weight of the 5 largest constituents"),
    S("The technology sector went from about a tenth of the index to @a more than a quarter in ten years.",
      tag("TECH SECTOR IN MSCI WORLD"),
      bars([("10 years ago", 10, "≈10%", "slate"), ("Today", 26, ">25%", "amber")], maxv=30, at="a")),
    S("To be clear, none of this is a conspiracy. It's simply how market cap indices work. When a company grows, you automatically own more of it.",
      head("Not a conspiracy."),
      sub("It's how {a:market-cap indices} work.")),
    S("And it's exactly why world ETFs did so well over the last decade. You rode the winners all the way up.",
      head("You rode the {g:winners} all the way up.")),
    S("Think about what that means. You never had to pick Nvidia. The index picked it for you, @a and kept adding more as the price went up.",
      head("The index picked {a:Nvidia} for you"),
      sub("…and bought more as the price {g:went up}.", at="a")),
    S("There's no rule in a market cap index that says: this is getting too expensive, let's take some money off the table. @a Price goes up, weight goes up. That's it.",
      head("No rule for “{a:too expensive}”."),
      sub("Price ↑ → weight ↑. That's it.", at="a")),
    S("But it works in both directions. @a When a giant falls, it falls with your money inside it.",
      head("It works in {a:both directions}."),
      sub("When a giant falls, it falls {r:with your money inside}.", at="a")),
    S("The E C B economists put it bluntly. Looking at past technology revolutions, @a a correction is likely, and euro area households would feel it mostly through their funds.",
      pill("ECB WARNING"),
      head("“A correction is {r:likely}.”", at="a"),
      sub("Exposure mostly through funds and ETFs"),
      src=SRC_ECB),
    S("Quick question before we go back in time.",
      tag("QUESTION 1/3", color="amber"),
      head("Quick question.")),
    S("In the year 2000, at the peak of the dot-com bubble, what share of the S and P five hundred did its ten largest companies make up?",
      tag("QUESTION 1/3", color="amber"),
      head("Year 2000: top 10 share of the {a:S&P 500}?", size=60),
      options(["15%", "26%", "40%"], correct=1, reveal="r")),
    S("Fifteen, twenty-six, or forty percent? Think about it. @r It was about twenty-six percent.",
      tag("QUESTION 1/3", color="amber"),
      head("Year 2000: top 10 share of the {a:S&P 500}?", size=60),
      options(["15%", "26%", "40%"], correct=1, reveal="r")),
    S("Today? It's close to @a forty. @b Higher than at the peak of the dot-com bubble.",
      tag("TOP 10 SHARE OF THE S&P 500"),
      bars([("2000", 26, "26%", "slate"), ("2026", 40, "≈40%", "red")], maxv=44, at="a"),
      sub("{r:Higher} than at the dot-com peak", at="b"),
      src="S&P 500 top-10 weight, 2000 vs 2026"),

    # ================================================================ CHAPTER 2
    S("Chapter two. We've been here before.", *chapter(2)),
    S("Twice, in fact. Let's start with the one most people forget.",
      head("Twice, in fact.")),
    S("December 1989. Japan is the hottest stock market on Earth. Banks, real estate, electronics. Everyone wants in.",
      tag("DECEMBER 1989"),
      head("Japan is the {a:hottest market} on Earth.")),
    S("At its peak, Japan made up @a around forty-two percent of the entire global stock market.",
      tag("JAPAN, SHARE OF GLOBAL STOCKS"),
      count(42, "{:.0f}%", color="amber", at="a"),
      src="justETF, Japan's peak weight in global equities, 1989"),
    S("Japanese stocks traded at around sixty times their earnings. People joked that the land under the Imperial Palace in Tokyo was worth more than all the real estate in California.",
      tag("JAPAN · 1989"),
      rows([("Price / earnings", "≈60×", "red")]),
      sub("Imperial Palace land > {a:all of California}?")),
    S("Bigger than the United States. If you bought the world in 1989, you mostly bought Japan.",
      tag("JAPAN, SHARE OF GLOBAL STOCKS"),
      count(42, "{:.0f}%", color="amber", frm=42),
      sub("If you bought the world, you mostly bought {a:Japan}.")),
    S("The Nikkei closed that year at almost thirty-nine thousand points. @a It would take thirty-four years, until February 2024, to see that level again.",
      tag("NIKKEI 225"),
      head("Back to the 1989 peak:"),
      count(34, "{:.0f} YEARS", color="red", at="a"),
      src="Nikkei 225: 38,916 on 29 Dec 1989; surpassed in Feb 2024"),
    S("Today Japan is around @a six percent of the world index.",
      tag("JAPAN IN THE WORLD INDEX"),
      bars([("1989", 42, "≈42%", "slate"), ("Today", 6, "≈6%", "amber")], maxv=46, at="a")),
    S("But here's the part almost nobody tells you. A world index investor in 1989 was not ruined.",
      head("A world investor was {g:not ruined}.")),
    S("As Japan shrank, the index automatically shifted toward everything else. @a In dollars, the world index was back to its 1989 level within about four years.",
      head("Back to the 1989 level:"),
      count(4, "≈{:.0f} YEARS", color="green", at="a"),
      src="MSCI World in USD, 1989 → 1993"),
    S("That's the self-cleaning feature of a market cap index. It concentrates into bubbles, @a but it also lets the losers shrink and the next winners grow.",
      head("The {a:self-cleaning} index"),
      rows([("Concentrates into bubbles", "✕", "red"), ("Lets losers shrink", "✓", "green")], at="a")),
    S("Now the second time. March 2000. The internet changes everything, and investors pay any price for it.",
      tag("MARCH 2000"),
      head("The internet changes {a:everything}.")),
    S("The top ten companies are about @a twenty-six percent of the S and P five hundred. @b Valuations hit forty-four times earnings, the highest ever recorded.",
      tag("MARCH 2000"),
      rows([("Top 10 share of S&P 500", "26%", "amber")], at="a"),
      rows([("Shiller CAPE", "44", "red")], at="b")),
    S("For a moment in March 2000, @a Cisco, a company that makes network equipment, was the most valuable company in the world.",
      tag("MARCH 2000"),
      head("World's most valuable company:", size=60),
      big("CISCO", color="amber", at="a")),
    S("Companies with no profits went public and doubled on their first day. If it had dot com in the name, people bought it.",
      tag("MARCH 2000"),
      head("No profits? {a:No problem.}"),
      sub("If it ended in “.com”, people bought it.")),
    S("Then it breaks. The Nasdaq one hundred falls @a more than eighty percent.",
      tag("NASDAQ-100 · 2000 → 2002"),
      big("−80%+", color="red", at="a")),
    S("It needs @a more than fifteen years to get back to its peak.",
      tag("NASDAQ-100"),
      head("Back to the March 2000 peak:"),
      big("15+ YEARS", color="red", at="a"),
      src="Nasdaq-100 peak 4,704.73 on 27 Mar 2000"),
    S("And no, Europe was not a safe place to hide. Telecom stocks were the European version of the bubble. The Euro Stoxx fifty lost @a about two thirds of its value from 2000 to 2003.",
      tag("EURO STOXX 50 · 2000 → 2003"),
      big("−⅔", color="red", at="a"),
      sub("Europe crashed {r:just as hard}"),
      src="Euro Stoxx 50: ≈5,464 (Mar 2000) → ≈1,850 (Mar 2003)"),
    S("Germany had its own story. Deutsche Telekom was sold to ordinary families as the people's share. @a At the peak in March 2000, it traded above one hundred euros.",
      tag("DEUTSCHE TELEKOM · “THE PEOPLE'S SHARE”"),
      rows([("March 2000", "≈€103", "amber")], at="a")),
    S("Two years later, @a it was below ten. Millions of first-time investors lost about ninety percent, and a whole generation of Germans swore off the stock market.",
      tag("DEUTSCHE TELEKOM · “THE PEOPLE'S SHARE”"),
      rows([("March 2000", "≈€103", "amber")]),
      rows([("2002", "<€10", "red")], at="a"),
      sub("A generation {r:swore off} stocks"),
      src="Deutsche Telekom share price, Xetra"),
    S("That's the hidden cost of a bubble. Not just the money. The people who never come back.",
      head("The hidden cost:"),
      sub("the people who {r:never come back}.")),
    S("So let's put then and now side by side.",
      table(["", "2000", "2026"], [])),
    S("Share of the top ten in the S and P five hundred: @a about twenty-six percent then, close to forty now.",
      table(["", "2000", "2026"], [("Top 10 in S&P 500", "26%", "≈40%")], at="a")),
    S("Valuations: @a forty-four then, around forty-one now.",
      table(["", "2000", "2026"], [("Top 10 in S&P 500", "26%", "≈40%"), ("Shiller CAPE", "44", "41")], at="a")),
    S("And the US share of the world index: @a roughly half back then. More than seventy percent today.",
      table(["", "2000", "2026"], [("Top 10 in S&P 500", "26%", "≈40%"), ("Shiller CAPE", "44", "41"),
                                   ("USA in MSCI World", "≈50%", ">70%")], at="a")),
    S("On paper, today looks just as stretched, and more concentrated.",
      table(["", "2000", "2026"], [("Top 10 in S&P 500", "26%", "≈40%"), ("Shiller CAPE", "44", "41"),
                                   ("USA in MSCI World", "≈50%", ">70%")]),
      sub("Just as stretched. {r:More concentrated.}")),
    S("There is one big difference. Today's giants make enormous profits. In 2000, plenty of internet darlings had no earnings at all.",
      head("One big difference:"),
      sub("Today's giants make {g:enormous profits}.")),
    S("But profitable doesn't mean cheap. @a Cisco was very profitable in 2000. Its share price still fell by more than eighty percent.",
      tag("CISCO · 2000 → 2002"),
      head("Profitable ≠ cheap"),
      big("−80%+", color="red", at="a")),
    S("A great company can still be a bad investment at the wrong price.",
      head("A great company can be a {r:bad investment}", size=64),
      sub("…at the wrong price.")),

    # ================================================================ CHAPTER 3
    S("Chapter three. The replay.", *chapter(3)),
    S("Here's the setup. Ten thousand euros into world stocks, on the last day of 1999. Right at the top.",
      tag("THE SETUP"),
      head("{a:€10,000} in world stocks"),
      sub("31 December 1999 · right at the top"),
      src=SRC_WORLD),
    S("M S C I World, dividends reinvested, measured in euros, after a zero point two percent yearly fee. No cherry picking.",
      tag("THE SETUP"),
      rows([("Index", "MSCI World", "white"), ("Currency", "EUR", "white"),
            ("Dividends", "reinvested", "white"), ("Fees", "0.2% / year", "white")]),
      src=SRC_WORLD),
    S("Question two. By the end of 2002, how much of your ten thousand euros was left?",
      tag("QUESTION 2/3", color="amber"),
      head("End of 2002: how much is {a:left}?", size=64),
      options(["€8,900", "€7,200", "€5,500"], correct=2, reveal="r"),
      src=SRC_WORLD),
    S("Eight thousand nine hundred, seven thousand two hundred, or five thousand five hundred? @r Five thousand five hundred.",
      tag("QUESTION 2/3", color="amber"),
      head("End of 2002: how much is {a:left}?", size=64),
      options(["€8,900", "€7,200", "€5,500"], correct=2, reveal="r"),
      src=SRC_WORLD),
    S("@a Forty-five percent gone in three years. And remember, this is the whole world index. Not a tech fund.",
      count(-45, "{:.0f}%", color="red", frm=0, size=150, at="a"),
      chart([world_series(2002)], draw="a", **CRASH_AXES),
      src=SRC_WORLD),
    S("Then the recovery starts. 2003, 2004, 2005. By the end of 2006, you're at @a eight thousand seven hundred. Almost there.",
      tag("THE RECOVERY"),
      chart([world_series(2006, frm=2002)], draw="s", **CRASH_AXES),
      sub("End of 2006: {a:€8,749}", at="a"),
      src=SRC_WORLD),
    S("And then, @a 2008.",
      tag("THE RECOVERY"),
      chart([world_series(2008, frm=2006)], draw="a", **CRASH_AXES),
      src=SRC_WORLD),
    S("By the end of 2008, your portfolio is worth @a five thousand three hundred euros.",
      count(5327, "€{:,.0f}", color="red", frm=8749, size=150, at="a"),
      chart([world_series(2008)], **CRASH_AXES),
      src=SRC_WORLD),
    S("Read that again. Nine years in, you have @a less money than at the bottom of the dot-com crash.",
      head("Nine years in…"),
      rows([("Bottom of the dot-com crash · 2002", "€5,515", "red"),
            ("Bottom of the financial crisis · 2008", "€5,327", "red")], at="a"),
      src=SRC_WORLD),
    S("So when are you finally back above ten thousand euros?",
      tag("QUESTION"),
      head("When are you back above {a:€10,000}?"),
      chart([world_series(2008)], **CRASH_AXES),
      src=SRC_WORLD),
    S("@a In 2013.",
      tag("BACK ABOVE €10,000"),
      chart([world_series(2013, frm=2008)], draw="a", **CRASH_AXES),
      src=SRC_WORLD),
    S("@a Thirteen years. Thirteen years of doing everything right, and having nothing to show for it.",
      count(13, "{:.0f} YEARS", color="red", at="a"),
      sub("of doing everything right"),
      src=SRC_WORLD),
    S("If you started investing in your thirties, you'd be close to fifty before you saw a profit.",
      head("Start at {a:35}…"),
      sub("first real profit at {r:48}")),
    S("And it wasn't a quiet thirteen years. You lived through two crashes of almost fifty percent each. @a Your bank advisor, the news, your friends, everyone told you stocks were dead.",
      head("Two crashes of {r:almost 50%}"),
      sub("“Stocks are dead.” — everyone", at="a")),
    S("By the way, if you saw my short on this, the start date there was January 2001, and the answer was twelve years. Starting at the very top makes it one year worse.",
      tag("FROM THE SHORTS"),
      rows([("Start Jan 2001", "12 years", "amber"), ("Start Dec 1999 (the top)", "13 years", "red")])),
    S("Now, the other side of the story. That same ten thousand euros, invested at the worst possible moment, @a is worth about forty-six thousand euros today.",
      tag("31 DEC 1999 → AUGUST 2026"),
      chart([world_series(2026.7, frm=2013)], draw="s", h=300, **WORLD_AXES),
      count(46032, "€{:,.0f}", color="green", frm=10000, size=140, at="a"),
      src=SRC_WORLD),
    S("That's about @a five point nine percent a year, for almost twenty-seven years. After the dot-com crash, after 2008, after Covid, after 2022.",
      tag("31 DEC 1999 → AUGUST 2026"),
      count(5.9, "{:.1f}% / YEAR", color="green", size=150, at="a"),
      src=SRC_WORLD),
    S("And before you say, yes, but inflation: prices in the euro area rose about seventy-six percent from 1999 to 2025. @a So in today's money, your ten thousand euros became roughly two and a half times as much. Still a real gain.",
      tag("ADJUSTED FOR INFLATION"),
      rows([("Euro area prices, 1999 → 2025", "+76%", "amber")]),
      rows([("Real growth of your €10,000", "≈ ×2.5", "green")], at="a"),
      src="Euro area HICP (ECB), Dec 1999 – Dec 2025"),
    S("And the crashes kept coming. In 2020, Covid sent markets down by a third in a few weeks. @a In 2022, world stocks lost almost thirteen percent in euros, while bonds fell too.",
      tag("AFTER 2013"),
      rows([("2020 · Covid crash", "≈ −33% in weeks", "red")]),
      rows([("2022 · world stocks in EUR", "−12.8%", "red")], at="a"),
      src=SRC_WORLD),
    S("Each one felt like the end of the world at the time. @a On this chart, they're small dents.",
      tag("31 DEC 1999 → AUGUST 2026"),
      chart([world_series(2026.7)], **WORLD_AXES),
      sub("At the time: the end of the world. Here: {a:small dents}.", at="a"),
      src=SRC_WORLD),
    S("So buying at the top did not ruin you. @a Selling at the bottom would have.",
      head("Buying at the top {g:didn't ruin you}."),
      head("Selling at the bottom {r:would have}.", at="a")),
    S("But most of you don't invest a lump sum on one day. You invest every month. So let's replay that too.",
      tag("THE SAVINGS PLAN"),
      head("Most of you invest {a:every month}.")),
    S("Three hundred euros a month, starting in January 2000. Straight into the crash.",
      tag("THE SAVINGS PLAN"),
      count(300, "€{:,.0f} / MONTH", size=150),
      sub("from January 2000 · straight into the crash")),
    S("End of 2002. You've put in @a ten thousand eight hundred euros. @b It's worth seven thousand two hundred.",
      tag("END OF 2002"),
      rows([("Put in", "€10,800", "white")], at="a"),
      rows([("Worth", "€7,265", "red")], at="b"),
      src="Monthly plan approximated with annual returns (mid-year contributions)"),
    S("End of 2008, after nine years of saving: @a thirty-two thousand four hundred in, @b twenty-three thousand four hundred left. That's the moment most people quit.",
      tag("END OF 2008"),
      rows([("Put in", "€32,400", "white")], at="a"),
      rows([("Worth", "€23,373", "red")], at="b"),
      src="Monthly plan approximated with annual returns (mid-year contributions)"),
    S("But those were the months when every three hundred euros bought the most shares. @a The crash years were your best buying years.",
      head("Every €300 bought {a:more shares}."),
      sub("The crash years were your {g:best buying years}.", at="a")),
    S("Today, you've put in ninety-six thousand euros. @a The plan is worth about four hundred and sixteen thousand.",
      tag("€300 / MONTH · JAN 2000 → AUG 2026"),
      chart([dict(x=PLAN_X, y=PLAN_PAID, upto=2026.7, color="slate", end_label=True),
             dict(x=PLAN_X, y=PLAN_V, upto=2026.7, color="green", end_label=True)],
            draw="s", xr=(1999, 2027), yr=(0, 450000), xticks=[2000, 2010, 2020],
            yticks=[(100000, "€100k"), (400000, "€400k")], h=300),
      count(415875, "€{:,.0f}", color="green", frm=0, size=130, at="a"),
      src="Monthly plan approximated with annual returns (mid-year contributions)"),
    S("The crash didn't hurt the monthly saver. It paid them. But only if they kept going.",
      head("The crash {g:paid} the monthly saver."),
      sub("…if they {a:kept going}.")),

    # ================================================================ CHAPTER 4
    S("Chapter four. The currency trap.", *chapter(4)),
    S("There's a layer most European investors completely forget. The dollar.",
      head("The layer everyone forgets:"),
      big("$ → €", color="amber")),
    S("More than seventy percent of your world ETF is priced in dollars. @a When the dollar falls against the euro, you lose money, even if American stocks don't move at all.",
      head("{a:70%+} of your ETF is in dollars"),
      sub("Dollar ↓ against the euro = {r:you lose}", at="a")),
    S("Here's a simple example. Say an American stock stays exactly flat in dollars for a year. @a But the euro rises ten percent. In euros, you just lost about nine percent. On a stock that didn't move.",
      tag("EXAMPLE"),
      rows([("Stock in USD", "0%", "white")]),
      rows([("Euro vs dollar", "+10%", "amber"), ("Your result in EUR", "≈ −9%", "red")], at="a")),
    S("And here's a very common misunderstanding. Many people buy the euro listed version of their ETF and think the currency risk is gone. @a It isn't.",
      head("Bought it in euros?"),
      sub("The currency risk {r:is still there}.", at="a")),
    S("What matters is not the currency you pay with. It's the currency the underlying companies are priced in. @a Apple is a dollar company, whether you buy it in Frankfurt, Milan, or New York.",
      head("What matters: the companies' currency"),
      chips(["Frankfurt", "Milan", "New York"], at="a"),
      sub("Apple is a {a:dollar company} everywhere.", at="a")),
    S("And in the dot-com crash, that's exactly what happened.",
      tag("EUR / USD")),
    S("In October 2000, one euro was worth just @a eighty-three cents. By the end of 2004, it was worth @b one dollar thirty-six.",
      tag("EUR / USD"),
      rows([("October 2000", "$0.83", "white")], at="a"),
      rows([("End of 2004", "$1.36", "amber")], at="b"),
      src="ECB euro reference rates"),
    S("For a euro investor, that move alone wiped out @a almost forty percent of the value of every dollar asset.",
      tag("DOLLAR ASSETS, MEASURED IN EUR"),
      count(-39, "{:.0f}%", color="red", frm=0, at="a"),
      sub("from the currency alone"),
      src="ECB euro reference rates"),
    S("Look at 2002. World stocks lost @a about twenty percent in dollars. @b In euros, they lost thirty-three.",
      tag("MSCI WORLD · 2002"),
      bars([("in USD", 20, "−20%", "slate")], maxv=40, at="a"),
      bars([("in EUR", 33, "−33%", "red")], maxv=40, at="b"),
      src="MSCI World net, 2002: −19.9% USD, −32.7% EUR"),
    S("Then 2008 did the opposite. In the panic, investors ran to the dollar, and the dollar rose. @a That cushioned the crash: minus forty-one percent in dollars, but minus thirty-seven in euros.",
      tag("MSCI WORLD · 2008"),
      bars([("in USD", 41, "−41%", "slate"), ("in EUR", 37, "−37%", "amber")], maxv=45, at="a"),
      src="MSCI World net, 2008: −40.7% USD, −37.3% EUR"),
    S("And this isn't ancient history. In 2025, the dollar fell sharply against the euro. @a World stocks gained around twenty percent in dollars, but only about seven percent for a euro investor.",
      tag("MSCI WORLD · 2025"),
      bars([("in USD", 21, "≈ +21%", "slate"), ("in EUR", 7.2, "≈ +7%", "amber")], maxv=25, at="a"),
      src=SRC_WORLD),
    S("So in a crash, the currency can be your airbag, @a or your second punch. And you don't get to choose in advance.",
      head("Your {g:airbag}…"),
      head("…or your {r:second punch}.", at="a")),
    S("Right now, the euro is around @a one dollar thirteen, its lowest level since May 2025, after both the Fed and the E C B raised rates in September.",
      tag("EUR / USD · TODAY"),
      big("$1.13", color="amber", at="a"),
      sub("lowest since May 2025"),
      src="EUR/USD, late September 2026"),
    S("If the dollar falls back from here while US stocks fall too, euro investors get hit twice.",
      head("Dollar ↓ + US stocks ↓"),
      sub("= euro investors {r:hit twice}")),
    S("Over the very long run, currency swings tend to wash out. Over five or ten years, they can decide whether you made money or not.",
      head("Long run: {g:washes out}."),
      sub("5 – 10 years: {r:can decide everything}.")),
    S("Euro hedged share classes remove this risk. But they cost a bit more, and they also remove the airbag. @a There's no free lunch here.",
      head("EUR-hedged ETFs"),
      rows([("Removes the second punch", "✓", "green"), ("Removes the airbag", "✕", "red"), ("Costs a bit more", "✕", "red")], at="a")),

    # ================================================================ CHAPTER 5
    S("Chapter five. The stress test.", *chapter(5)),
    S("Now the real experiment. What would a crash do to the portfolios people actually hold today?",
      head("What would a crash do {a:today}?")),
    S("I split the world index into four buckets.",
      tag("TODAY'S MSCI WORLD, IN 4 BUCKETS")),
    S("The AI giants, @a about twenty-five percent. @b The rest of the US, about forty-six. @c Other developed markets, about twenty-nine. @d And for global funds, emerging markets.",
      tag("TODAY'S MSCI WORLD, IN 4 BUCKETS"),
      bars([("AI giants", 25, "25%", "red")], maxv=50, at="a"),
      bars([("Rest of USA", 46, "46%", "amber")], maxv=50, at="b"),
      bars([("Other developed", 29, "29%", "slate")], maxv=50, at="c"),
      bars([("Emerging (All-World)", 10.5, "≈10%", "slate")], maxv=50, at="d")),
    S("Why a separate bucket for the AI giants? Because if this is a bubble, that's where it is. The chips, the cloud, the data centres. That's the money betting on AI.",
      head("If it's a bubble, {a:it's here}."),
      chips(["Chips", "Cloud", "Data centres"])),
    S("Then I ran two scenarios, based on what really happened in past crashes. These are scenarios, not forecasts.",
      head("Two scenarios."),
      sub("Based on past crashes · {a:not forecasts}")),
    S("Scenario A: an AI-only correction. @a The AI giants fall fifty percent. @b The rest of the US falls ten. @c Other markets dip a little.",
      pill("SCENARIO A"),
      head("AI-only correction", size=64),
      rows([("AI giants", "−50%", "red")], at="a"),
      rows([("Rest of USA", "−10%", "amber")], at="b"),
      rows([("Other developed / emerging", "−5% / −15%", "slate")], at="c")),
    S("Scenario B: a full dot-com replay. @a The AI giants lose seventy percent, @b and like in 2000, everything else falls hard too.",
      pill("SCENARIO B"),
      head("Full dot-com replay", size=64),
      rows([("AI giants", "−70%", "red")], at="a"),
      rows([("Rest of USA / other developed", "−35% / −40%", "red"), ("Emerging", "−45%", "red")], at="b")),
    S("The maths is deliberately simple. For each portfolio, I multiplied its weight in each bucket by that bucket's loss, and added it all up. @a You could redo it on a napkin.",
      tag("THE METHOD"),
      head("weight × loss, {a:added up}"),
      sub("Simple enough to redo on a napkin.", at="a")),
    S("Scenario B isn't made up. From 2000 to 2002, the big tech names of that era lost seventy to ninety percent. The S and P five hundred lost about half. And as we saw, Europe lost about two thirds.",
      pill("SCENARIO B"),
      rows([("Big tech 2000 → 2002", "−70 to −90%", "red"), ("S&P 500", "≈ −50%", "red"), ("Euro Stoxx 50", "≈ −66%", "red")])),
    S("Let's start with scenario A. A plain M S C I World ETF loses @a about eighteen and a half percent.",
      pill("SCENARIO A"),
      bars([("MSCI World", 18.6, "−18.6%", "red")], maxv=50, at="a")),
    S("Now, many people think: I'll switch to an All-World fund, with emerging markets. @a That gets you to minus eighteen point two. Almost no difference.",
      pill("SCENARIO A"),
      bars([("MSCI World", 18.6, "−18.6%", "red")], maxv=50),
      bars([("All-World / ACWI", 18.2, "−18.2%", "red")], maxv=50, at="a")),
    S("Why? Because emerging markets are full of AI too. Taiwan and Korea are home to some of the biggest chipmakers on the planet.",
      head("Emerging markets are {a:full of AI} too."),
      chips(["TSMC", "Samsung", "SK Hynix"])),
    S("An equal weight world fund, where every company gets the same slice, @a loses only seven percent.",
      pill("SCENARIO A"),
      bars([("MSCI World", 18.6, "−18.6%", "red"), ("All-World / ACWI", 18.2, "−18.2%", "red")], maxv=50),
      bars([("World Equal Weight", 7.3, "−7.3%", "amber")], maxv=50, at="a")),
    S("Europe only: @a minus five. @b And a sixty forty portfolio, sixty percent world stocks and forty percent euro government bonds: minus nine.",
      pill("SCENARIO A"),
      bars([("MSCI World", 18.6, "−18.6%", "red"), ("All-World / ACWI", 18.2, "−18.2%", "red"),
            ("World Equal Weight", 7.3, "−7.3%", "amber")], maxv=50),
      bars([("Europe only", 5, "−5%", "green")], maxv=50, at="a"),
      bars([("60/40 World + euro bonds", 9.1, "−9.1%", "green")], maxv=50, at="b")),
    S("Equal weight does well here for an obvious reason: the AI giants are just a handful of names out of more than thirteen hundred. @a In an equal weight fund, they're less than one percent of your money.",
      head("Equal weight:"),
      sub("AI giants = {g:less than 1%} of your money", at="a")),
    S("But remember, Europe has its own giants too. A few companies like A S M L, S A P and Novo Nordisk drive a big part of European returns. Concentration isn't only an American thing.",
      tag("EUROPE'S OWN GIANTS"),
      chips(["ASML", "SAP", "Novo Nordisk"]),
      sub("Concentration isn't {a:only American}.")),
    S("In an AI-only correction, the alternatives really work. But now, scenario B.",
      pill("SCENARIO B"),
      head("Now, the {r:full replay}.")),
    S("M S C I World: @a minus forty-five percent. All-World: @b also minus forty-five.",
      pill("SCENARIO B"),
      bars([("MSCI World", 45.2, "−45.2%", "red")], maxv=50, at="a"),
      bars([("All-World / ACWI", 45.2, "−45.2%", "red")], maxv=50, at="b")),
    S("Equal weight: @a minus thirty-eight. Europe only: @b minus forty.",
      pill("SCENARIO B"),
      bars([("MSCI World", 45.2, "−45.2%", "red"), ("All-World / ACWI", 45.2, "−45.2%", "red")], maxv=50),
      bars([("World Equal Weight", 38.5, "−38.5%", "red")], maxv=50, at="a"),
      bars([("Europe only", 40, "−40%", "red")], maxv=50, at="b")),
    S("And the sixty forty: @a minus twenty-four.",
      pill("SCENARIO B"),
      bars([("MSCI World", 45.2, "−45.2%", "red"), ("All-World / ACWI", 45.2, "−45.2%", "red"),
            ("World Equal Weight", 38.5, "−38.5%", "red"), ("Europe only", 40, "−40%", "red")], maxv=50),
      bars([("60/40 World + euro bonds", 23.9, "−23.9%", "amber")], maxv=50, at="a")),
    S("This is the uncomfortable result. In a real crash, switching from one stock index to another barely matters. @a The only thing that really changed the outcome was owning something that isn't stocks.",
      head("Swapping stock indices {r:barely matters}."),
      sub("What changed the outcome: owning {a:something that isn't stocks}.", at="a")),
    S("That doesn't make equal weight or All-World bad ideas. They spread your bets more evenly. @a Since 2000, equal weight even edged out the standard world index, about seven point eight percent a year versus seven point five, in dollars. They're just not crash protection.",
      tag("SINCE DEC 2000 · PER YEAR, USD"),
      bars([("MSCI World", 7.46, "7.46%", "slate"), ("MSCI World Equal Weight", 7.83, "7.83%", "amber")], maxv=9, at="a"),
      src="justETF index comparison, as of Jan 2026"),
    S("And we don't have to guess. Here's the real sixty forty, replayed from the end of 1999, with yearly rebalancing.",
      tag("€10,000 · 31 DEC 1999"),
      chart([world_series(2013, color="slate", end_label=False),
             dict(x=X, y=SIXTY40, upto=2013, color="green", end_label=False)], draw="s", **CRASH_AXES),
      src="60% MSCI World + 40% euro government bonds, rebalanced yearly, in EUR"),
    S("At the end of 2002, it was down @a twenty-one percent instead of forty-five.",
      tag("END OF 2002"),
      rows([("100% world stocks", "−45%", "red"), ("60/40", "−21%", "amber")], at="a"),
      src="60% MSCI World + 40% euro government bonds, rebalanced yearly, in EUR"),
    S("It was back above ten thousand euros in @a 2005. Eight years earlier than the all-stock portfolio.",
      tag("BACK ABOVE €10,000"),
      rows([("100% world stocks", "2013", "red"), ("60/40", "2005", "green")], at="a")),
    S("The price? Today it's worth about @a thirty-eight thousand six hundred, instead of forty-six thousand. Less growth, in exchange for much smaller holes.",
      tag("AUGUST 2026"),
      rows([("100% world stocks", "€46,032", "green"), ("60/40", "€38,606", "amber")], at="a")),
    S("There's a hidden engine in that sixty forty: rebalancing. Every year it goes back to sixty percent stocks. @a So at the end of 2002 and 2008, it was forced to sell bonds and buy cheap stocks. Exactly when nobody wanted to.",
      head("The hidden engine: {a:rebalancing}"),
      sub("2002 & 2008: sell bonds → {g:buy cheap stocks}", at="a")),
    S("But there's a warning label. @a In 2022, euro government bonds lost about eighteen percent, in the same year stocks fell.",
      pill("WARNING"),
      head("2022: euro govt bonds"),
      count(-18, "{:.0f}%", color="red", frm=0, at="a"),
      src="Euro area government bonds, all maturities, 2022"),
    S("Bonds protected you in 2000 and 2008, when interest rates fell. They don't protect you when inflation and rates are rising. @a And inflation in the euro area is back above three percent.",
      head("Bonds protect when {g:rates fall}…"),
      sub("not when {r:inflation} is rising.", at="a"),
      rows([("Euro area inflation, August 2026", "3.3%", "red"), ("ECB deposit rate", "2.50%", "amber")], at="a"),
      src="Eurostat / ECB, September 2026"),
    S("And one more honest point. Over the last decade, almost every one of these safer alternatives trailed the plain world index. Protection always has a price.",
      head("Protection always has a {a:price}.")),

    # ================================================================ CHAPTER 6
    S("Chapter six. What actually protected you.", *chapter(6)),
    S("So what really worked for European investors through the last two crashes? Three things. @a And none of them is a clever ETF.",
      head("Three things."),
      sub("None of them is a {a:clever ETF}.", at="a")),
    S("Number one. Matching your money to your time horizon.",
      tag("1 / 3", color="amber"),
      head("Match your money to your {a:time horizon}.")),
    S("Your world ETF needed thirteen years to recover from the dot-com top. @a Money you need in the next five years has no business being one hundred percent in stocks.",
      tag("1 / 3", color="amber"),
      rows([("Recovery after the 1999 top", "13 years", "red")]),
      rows([("Money needed within 5 years", "not 100% stocks", "amber")], at="a")),
    S("Picture someone who's fifty-eight in 2026 and plans to retire at sixty-five. If a dot-com style crash hits next year, a thirteen year recovery takes them to seventy-one. @a That's why the mix should change as the date gets closer.",
      tag("EXAMPLE"),
      rows([("Age today", "58", "white"), ("Planned retirement", "65", "amber")]),
      rows([("Back to even after a 13-year recovery", "71", "red")], at="a")),
    S("That's not about being scared. It's about not being forced to sell at the bottom because you need the money for a house, a car, or your retirement.",
      head("Never be {r:forced to sell}"),
      sub("House · car · retirement")),
    S("The simplest tool for that isn't an ETF at all. @a It's an emergency fund. A few months of expenses in cash, so a broken car or a lost job never forces you to sell your ETF at minus forty percent.",
      tag("1 / 3", color="amber"),
      head("The simplest crash protection:"),
      big("CASH BUFFER", color="green", size=130, at="a"),
      sub("a few months of expenses")),
    S("Number two. Keep buying.",
      tag("2 / 3", color="amber"),
      head("Keep {a:buying}.")),
    S("The monthly saver who kept going through 2002 and 2008 turned ninety-six thousand euros into about four hundred and sixteen thousand. @a The crashes were where most of that came from.",
      tag("2 / 3", color="amber"),
      rows([("Put in", "€96,000", "white"), ("Worth", "≈€416,000", "green")]),
      sub("The crashes were the {g:best buying years}.", at="a")),
    S("The practical way to do that is boring on purpose: a standing order on the same day every month, set up once, and then left alone. @a Most European brokers offer savings plans for free or close to it.",
      tag("2 / 3", color="amber"),
      head("Boring {a:on purpose}."),
      sub("Same day · every month · automatic", at="a")),
    S("Number three. And this is the one that matters most. Not selling.",
      tag("3 / 3", color="amber"),
      head("{a:Not selling}.")),
    S("Let's meet two investors. Both put ten thousand euros into world stocks at the end of 1999.",
      tag("TWO INVESTORS"),
      rows([("Investor A", "€10,000", "white"), ("Investor B", "€10,000", "white")])),
    S("At the end of 2002, with forty-five percent gone, @a investor A panics. Sells everything. Puts the five thousand five hundred euros left into a savings account paying two percent a year.",
      tag("END OF 2002"),
      rows([("Investor A", "SELLS", "red")], at="a"),
      sub("€5,515 → savings account at 2%", at="a")),
    S("Investor B does nothing. Doesn't sell. Doesn't check the app. Just waits.",
      tag("END OF 2002"),
      rows([("Investor A", "SELLS", "red"), ("Investor B", "WAITS", "green")])),
    S("Today, investor A has @a about eight thousand eight hundred euros. Less than they started with, twenty-seven years later.",
      tag("AUGUST 2026"),
      rows([("Investor A", "€8,813", "red")], at="a")),
    S("And investor B has @a forty-six thousand.",
      tag("AUGUST 2026"),
      rows([("Investor A", "€8,813", "red")]),
      rows([("Investor B", "€46,032", "green")], at="a")),
    S("And here's the cruel part. Investor A didn't feel stupid in 2003. They felt smart. They had avoided the pain. Every bad headline for the next ten years told them they were right.",
      head("Investor A felt {a:smart}."),
      sub("Every headline for 10 years said they were right.")),
    S("That's why panic selling is so dangerous. It feels like the responsible thing to do, @a and the bill only arrives many years later.",
      head("It feels {g:responsible}…"),
      sub("…the bill arrives {r:years later}.", at="a")),

    # ================================================================ CHAPTER 7
    S("Chapter seven. The number that matters.", *chapter(7)),
    S("Here it is. @a Thirty-seven thousand euros.",
      count(37219, "€{:,.0f}", color="amber", frm=0, size=180, at="a")),
    S("That's the difference between investor A and investor B. Same money, same index, same start date, same crash.",
      count(37219, "€{:,.0f}", color="amber", frm=37219, size=180),
      sub("Same money. Same index. Same start. {a:Same crash.}")),
    S("The only difference was one decision, made in a moment of fear. That's the price of panic.",
      count(37219, "€{:,.0f}", color="red", frm=37219, size=180),
      head("The {r:price of panic}.")),
    S("No ETF, no equal weighting, no clever strategy came anywhere close to that number in this replay. @a Your behaviour mattered more than your fund.",
      head("Your {a:behaviour} mattered more"),
      head("than your {a:fund}.", at="a")),
    S("Let's recap what the euro data showed us.",
      tag("RECAP")),
    S("Buying at the dot-com top: @a forty-five percent down, and thirteen years to get back to even.",
      tag("RECAP"),
      rows([("Lump sum at the 1999 top", "−45% · 13 years", "red")], at="a")),
    S("The dollar: @a it can add a second punch of up to forty percent, or soften the blow.",
      tag("RECAP"),
      rows([("Lump sum at the 1999 top", "−45% · 13 years", "red")]),
      rows([("Currency", "up to −39% / airbag", "amber")], at="a")),
    S("Swapping one stock index for another: @a helps in a tech-only correction, barely matters in a full crash.",
      tag("RECAP"),
      rows([("Lump sum at the 1999 top", "−45% · 13 years", "red"), ("Currency", "up to −39% / airbag", "amber")]),
      rows([("Swapping stock indices", "small help", "slate")], at="a")),
    S("A sixty forty with euro bonds: @a back to even eight years sooner, for a smaller final result.",
      tag("RECAP"),
      rows([("Lump sum at the 1999 top", "−45% · 13 years", "red"), ("Currency", "up to −39% / airbag", "amber"),
            ("Swapping stock indices", "small help", "slate")]),
      rows([("60/40 with euro bonds", "8 years faster", "green")], at="a")),
    S("The monthly saver: @a money multiplied by more than four. And panic selling: @b a thirty-seven thousand euro mistake.",
      tag("RECAP"),
      rows([("Lump sum at the 1999 top", "−45% · 13 years", "red"), ("Currency", "up to −39% / airbag", "amber"),
            ("Swapping stock indices", "small help", "slate"), ("60/40 with euro bonds", "8 years faster", "green")]),
      rows([("Monthly saver", "×4.3", "green")], at="a"),
      rows([("Panic selling", "−€37,219", "red")], at="b")),
    S("And this isn't just my replay. Morningstar's yearly Mind the Gap study keeps finding the same thing: @a investors earn less than the funds they own, because they buy after the rises and sell after the falls.",
      tag("MORNINGSTAR · MIND THE GAP"),
      head("Investors earn {r:less} than their funds", size=64),
      sub("Buy after rises · sell after falls", at="a")),
    S("So, is AI a bubble? Honestly, I don't know. And neither does anyone on YouTube who tells you they do.",
      head("Is AI a bubble?"),
      sub("Honestly? {a:Nobody knows.}")),
    S("And even if it is a bubble, that doesn't mean AI is fake. The internet wasn't fake either. Amazon survived the dot-com crash and became one of the biggest companies on Earth.",
      head("The internet {g:wasn't fake} either."),
      chips(["Amazon"])),
    S("But between 1999 and 2001, @a Amazon's share price still fell by more than ninety percent. Being right about the technology is not the same as being right about the price.",
      tag("AMAZON · 1999 → 2001"),
      big("−90%+", color="red", at="a"),
      sub("Right technology. {r:Wrong price.}")),
    S("The E C B thinks a correction is likely. But bubbles can also run much longer than anyone expects. @a In 1996, Alan Greenspan warned about irrational exuberance. The Nasdaq then almost quadrupled before it crashed.",
      tag("DECEMBER 1996"),
      head("“Irrational exuberance”"),
      sub("Nasdaq then {a:almost ×4} before the crash", at="a")),
    S("What I do know is this: we have twenty-seven years of real euro data, two full bubbles, and the same lesson every single time.",
      head("27 years. 2 bubbles."),
      sub("{a:Same lesson} every time.")),
    S("The crash itself never decided who ended up rich. @a What people did during the crash did.",
      head("The crash didn't decide."),
      head("{a:What people did} decided.", at="a")),
    S("So instead of predicting, here's what I'd check in my own portfolio. This is not financial advice, just a checklist.",
      tag("MY CHECKLIST · NOT ADVICE"),
      head("Check, don't {a:predict}.")),
    S("One. Look at your ETF's top ten and its country weights. @a Know what you actually own.",
      tag("MY CHECKLIST · NOT ADVICE"),
      rows([("1", "Know your top 10 and country weights", "amber")], at="a")),
    S("Two. Set your mix of stocks and bonds by when you need the money, not by the headlines.",
      tag("MY CHECKLIST · NOT ADVICE"),
      rows([("1", "Know your top 10 and country weights", "amber"),
            ("2", "Stock/bond mix by your time horizon", "amber")])),
    S("Three. If you diversify away from the giants, do it for the long run, knowing it can lag for a decade.",
      tag("MY CHECKLIST · NOT ADVICE"),
      rows([("1", "Know your top 10 and country weights", "amber"),
            ("2", "Stock/bond mix by your time horizon", "amber"),
            ("3", "Diversify for the long run, or not at all", "amber")])),
    S("Four. Automate your monthly plan, so a scary headline can't stop it.",
      tag("MY CHECKLIST · NOT ADVICE"),
      rows([("1", "Know your top 10 and country weights", "amber"),
            ("2", "Stock/bond mix by your time horizon", "amber"),
            ("3", "Diversify for the long run, or not at all", "amber"),
            ("4", "Automate your monthly plan", "amber")])),
    S("And five. Write down today what you will do if your portfolio drops forty percent. Decide now, while you're calm.",
      tag("MY CHECKLIST · NOT ADVICE"),
      rows([("1", "Know your top 10 and country weights", "amber"),
            ("2", "Stock/bond mix by your time horizon", "amber"),
            ("3", "Diversify for the long run, or not at all", "amber"),
            ("4", "Automate your monthly plan", "amber"),
            ("5", "Write down your crash plan today", "green")])),
    S("Question three. And be honest. If your portfolio dropped forty-five percent next year, what would you do?",
      tag("QUESTION 3/3", color="amber"),
      head("Your portfolio drops {r:45%}. You…", size=64),
      options(["SELL", "STOP BUYING", "KEEP GOING"], countdown=False)),
    S("A, sell. B, stop buying. Or C, keep going. @a Tell me in the comments.",
      pill("BE HONEST"),
      head("What would {a:you} do?"),
      boxes(["A", "B", "C"], at="a")),
    S("If you want to see how a crash right before retirement changes everything, watch my video where I simulated ten thousand European retirements. @a It's on my channel.",
      card("FULL VIDEO", "The 4% Rule in Europe: I Simulated 10,000 Retirements", at="a")),
    S("And if you want more real euro data instead of hype, subscribe. Every video on this channel is built on numbers you can check.",
      head("Real euro data. {a:No hype.}"),
      sub("Subscribe for the next simulation")),
    S("Thanks for watching. See you in the next one.",
      head("THE AI BUBBLE {a:IN EUROPE}", size=96),
      sub("Data, not hype. · {a:EuroindexLab}"),
      src="Not financial advice. Past performance does not guarantee future results."),
]

CHAPTER_STARTS = [i for i, s in enumerate(SEGMENTS) if s["text"].startswith("Chapter ")]
