"""Narration + scenes (v2, fast cut) for:
"The AI Bubble in Europe: I Replayed the Dot-Com Crash on Your World ETF"

Each S(...) is one narration segment (usually one sentence) and the scene shown
while it is spoken. Q(...) is a silent beat (pause & guess, countdowns).
Tokens starting with '@' in the narration are reveal markers: an element with
at='x' appears when the narrator reaches the word that follows '@x'; with
until='x' it leaves at that word; elements sharing slot='...' take turns in
the same place. Visual markup: {a:text} amber, {r:text} red, {g:text} green.
The spoken words must stay identical to the recorded narration (assets/tts).
"""
from data import MSCI_WORLD_EUR, EURO_GOV_BONDS, lump_sum_path, mix, monthly_plan

# ---------------------------------------------------------------- datasets
X = [1999] + list(range(2000, 2026)) + [2026 + 8 / 12]
WORLD = lump_sum_path(MSCI_WORLD_EUR)
SIXTY40 = lump_sum_path(mix(MSCI_WORLD_EUR, EURO_GOV_BONDS, 0.6))
PLAN = monthly_plan(MSCI_WORLD_EUR, start=2000)
PLAN_X = [1999] + [p[0] if p[0] < 2026 else 2026 + 8 / 12 for p in PLAN]
PLAN_V = [0] + [p[1] for p in PLAN]
PLAN_PAID = [0] + [p[2] for p in PLAN]

# Nikkei 225, year-end closes (approx.), 1989-2024
NIKKEI = [38916, 23849, 22984, 16925, 17417, 19723, 19868, 19361, 15259, 13842, 18934, 13786,
          10543, 8579, 10677, 11489, 16111, 17226, 15308, 8860, 10546, 10229, 8455, 10395,
          16291, 17451, 19034, 19114, 22765, 20015, 23657, 27444, 28792, 26095, 33464, 39895]
NIKKEI_X = list(range(1989, 2025))
# EUR/USD, year-end ECB reference rates (approx.), 1999-2025 + late Sep 2026
EURUSD = [1.0070, 0.9305, 0.8813, 1.0487, 1.2630, 1.3621, 1.1797, 1.3170, 1.4721, 1.3917, 1.4406,
          1.3362, 1.2939, 1.3194, 1.3791, 1.2141, 1.0887, 1.0541, 1.1993, 1.1450, 1.1234, 1.2271,
          1.1326, 1.0666, 1.1050, 1.0389, 1.1740, 1.1350]
EURUSD_X = list(range(1999, 2026)) + [2026.75]

SRC_WORLD = "MSCI World, net, in EUR, after 0.2% fees · year-end values · 2026 = end of August"
SRC_ECB = "ECB Blog, “The AI boom: rational enthusiasm or the next dot-com bubble?”, Aug 2026"
SRC_PLAN = "Monthly plan approximated with annual returns (mid-year contributions)"
SRC_SCEN = "Illustrative scenarios on today's MSCI World weights · not a forecast"


def S(narration, *elements, src=None, cam=None):
    return dict(text=narration, elements=list(elements), src=src, cam=cam)


def Q(hold, *elements, src=None):
    """Silent beat (no narration) of `hold` seconds."""
    return dict(text="", hold=hold, elements=list(elements), src=src, cam="none")


def E(kind, **kw):
    kw["kind"] = kind
    return kw


def pill(t, **k): return E("pill", text=t, **k)
def tag(t, color="muted", **k): return E("tag", text=t, color=color, **k)
def head(t, size=84, **k): return E("head", text=t, size=size, **k)
def sub(t, size=50, **k): return E("sub", text=t, size=size, **k)
def big(t, color="amber", size=200, **k): return E("big", text=t, color=color, size=size, **k)
def count(to, fmt, color="amber", size=200, frm=0, **k):
    return E("big", text=None, to=to, frm=frm, fmt=fmt, color=color, size=size, **k)
def chips(items, **k): return E("chips", items=items, **k)
def rows(items, **k): return E("rows", items=items, **k)
def bars(items, maxv=None, **k): return E("bars", items=items, maxv=maxv, **k)
def options(items, correct=None, reveal=None, countdown=True, **k):
    return E("options", items=items, correct=correct, reveal=reveal, countdown=countdown, **k)
def waffle(groups, **k): return E("waffle", groups=groups, **k)
def boxes(items, note="comment below", **k): return E("boxes", items=items, note=note, **k)
def table(header, items, **k): return E("table", header=header, items=items, **k)
def chart(series, **k): return E("chart", series=series, **k)
def card(label, title, **k): return E("card", label=label, title=title, **k)
def donut(value, label, color="amber", **k): return E("donut", value=value, label=label, color=color, **k)
def versus(left, right, notes=None, **k): return E("versus", left=left, right=right, notes=notes, **k)
def timeline(items, **k): return E("timeline", items=items, **k)
def ticker(items, **k): return E("ticker", items=items, **k)
def subscribe(**k): return E("subscribe", **k)
def pause(text="PAUSE & GUESS", **k): return E("pause", text=text, **k)
def timer(seconds=3, **k): return E("timer", seconds=seconds, **k)
def stamp(t, color="red", angle=8, size=84, **k): return E("stamp", text=t, color=color, angle=angle, size=size, **k)
def strike(t, size=170, **k): return E("strike2", text=t, size=size, **k)


def world_series(upto, frm=None, color="amber", end_label=True, data=None):
    return dict(x=X, y=data or WORLD, upto=upto, frm=frm, color=color, end_label=end_label)


WORLD_AXES = dict(xr=(1999, 2027), yr=(0, 50000), xticks=[2000, 2005, 2010, 2015, 2020, 2025],
                  yticks=[(10000, "€10k"), (25000, "€25k"), (50000, "€50k")], ref=10000)
CRASH_AXES = dict(xr=(1999, 2014), yr=(4000, 11000), xticks=[2000, 2004, 2008, 2012],
                  yticks=[(5000, "€5k"), (10000, "€10k")], ref=10000)
NIKKEI_AXES = dict(xr=(1989, 2025), yr=(5000, 42000), xticks=[1990, 2000, 2010, 2020],
                   yticks=[(10000, "10k"), (38916, "38.9k")], ref=38916)
FX_AXES = dict(xr=(1999, 2027), yr=(0.8, 1.6), xticks=[2000, 2005, 2010, 2015, 2020, 2025],
               yticks=[(1.0, "$1.00"), (1.5, "$1.50")], ref=1.0)

CH = ["What you really own", "We've been here before", "The replay",
      "The currency trap", "The stress test", "What actually protected you",
      "The number that matters"]


def chapter(i):
    return [E("chapter_card", n=i, title=CH[i - 1])]


Q1 = options(["15%", "26%", "40%"], correct=1, reveal="r")
Q1H = head("Year 2000: top 10 share of the {a:S&P 500}?", size=66)
Q2 = options(["€8,900", "€7,200", "€5,500"], correct=2, reveal="r")
Q2H = head("End of 2002: how much is {a:left}?", size=66)
QR = options(["2005", "2009", "2013"], correct=2, reveal="a", countdown=False)
QRH = head("When are you back above {a:€10,000}?", size=66)
QX = options(["MSCI World", "All-World / ACWI", "World Equal Weight"], correct=2, reveal="a", countdown=False)
CHECK = [("1", "Know your top 10 and country weights", "amber"),
         ("2", "Stock/bond mix by your time horizon", "amber"),
         ("3", "Diversify for the long run, or not at all", "amber"),
         ("4", "Automate your monthly plan", "amber"),
         ("5", "Write down your crash plan today", "green")]
RECAP = [("Lump sum at the 1999 top", "−45% · 13 years", "red"), ("Currency", "up to −39% / airbag", "amber"),
         ("Swapping stock indices", "small help", "slate"), ("60/40 with euro bonds", "8 years faster", "green"),
         ("Monthly saver", "×4.3", "green"), ("Panic selling", "−€37,219", "red")]
SCEN_A = [("MSCI World", 18.6, "−18.6%", "red"), ("All-World / ACWI", 18.2, "−18.2%", "red"),
          ("World Equal Weight", 7.3, "−7.3%", "amber"), ("Europe only", 5, "−5%", "green"),
          ("60/40 World + euro bonds", 9.1, "−9.1%", "green")]
SCEN_B = [("MSCI World", 45.2, "−45.2%", "red"), ("All-World / ACWI", 45.2, "−45.2%", "red"),
          ("World Equal Weight", 38.5, "−38.5%", "red"), ("Europe only", 40, "−40%", "red"),
          ("60/40 World + euro bonds", 23.9, "−23.9%", "amber")]
TBL = [("Top 10 in S&P 500", "26%", "≈40%"), ("Shiller CAPE", "44", "41"), ("USA in MSCI World", "≈50%", ">70%")]
GIANTS = ["Nvidia", "Microsoft", "Apple", "Broadcom", "Amazon", "Alphabet", "Meta"]
NEWS = [("NVIDIA −3.4%", "red"), ("NASDAQ-100 −$600B IN 2 DAYS", "red"), ("ECB HIKES TO 2.50%", "amber"),
        ("EURO AREA INFLATION 3.3%", "amber"), ("“LATE-STAGE AI BUBBLE”", "red"), ("NASDAQ +$3T FROM THE LOW", "green")]

SEGMENTS = [
    # ================================================================ COLD OPEN
    S("@a Four hundred and forty billion euros.",
      count(440, "€{:,.0f} BILLION", size=180, at="a"), src=SRC_ECB),
    S("That's how much households in Europe hold in American tech stocks, according to economists at the European Central Bank.",
      count(440, "€{:,.0f} BILLION", size=180, frm=440),
      sub("held by EU households in {a:US tech stocks}"),
      pill("SOURCE: ECB ECONOMISTS"), src=SRC_ECB),
    S("And here's the part that got my attention: @a most of them don't even know it.",
      count(440, "€{:,.0f} BILLION", size=180, frm=440),
      sub("held by EU households in {a:US tech stocks}"),
      stamp("THEY DON'T KNOW", at="a"), src=SRC_ECB),
    S("And it's not just households.",
      head("It's not just {a:households}.")),
    S("According to the same analysis, insurance companies and pension funds have a similar exposure to big tech.",
      chips(["Households", "Insurers", "Pension funds"]),
      sub("Similar exposure to {a:big tech}"), src=SRC_ECB),
    S("@a So even your pension may be making the same bet.",
      head("Even your {a:pension}…", at="a"),
      stamp("SAME BET", color="amber", angle=-6)),
    S("Because they never bought Nvidia.",
      chips(["Nvidia"], strike=True)),
    S("They never bought Microsoft.",
      chips(["Nvidia", "Microsoft"], strike=True)),
    S("@a They bought a world ETF.",
      head("They bought a {a:world ETF}.", size=100, at="a")),
    S("One fund. Thousands of companies.",
      big("1 FUND", color="amber", size=150),
      sub("{a:Thousands} of companies")),
    S("@a Safe, simple, diversified.",
      chips(["Safe", "Simple", "Diversified"], at="a")),
    S("At least, that's the idea.",
      chips(["Safe", "Simple", "Diversified"]),
      stamp("THAT'S THE IDEA", color="amber", angle=-7)),
    S("Now look at what happened in September.",
      tag("SEPTEMBER 2026", color="amber"),
      head("Look at {a:September}."),
      ticker(NEWS)),
    S("In the middle of the month, the Nasdaq one hundred lost more than @a six hundred billion dollars in two days.",
      tag("NASDAQ-100 · 14–15 SEP"),
      count(-600, "−${:,.0f}B", color="red", at="a"),
      sub("in two days"), ticker(NEWS),
      src="Nasdaq-100 market value, 14–15 Sep 2026"),
    S("Then, within a week, @a it bounced back by trillions.",
      tag("…WITHIN A WEEK"),
      big("+$3T", color="green", at="a"), ticker(NEWS),
      src="Nasdaq-100 market value added from the 15 Sep low"),
    S("Fear, then greed, then fear again.",
      chips(["Fear", "Greed", "Fear again"]), ticker(NEWS)),
    S("Valuations in the US are at the @a second highest level in more than a hundred and fifty years.",
      tag("S&P 500 · SHILLER CAPE"),
      count(41, "{:.0f}", color="amber", at="a"),
      sub("2nd highest in {a:150+ years}"), src="Shiller CAPE, September 2026"),
    S("The only time they were higher?",
      tag("S&P 500 · SHILLER CAPE"),
      head("Only one time {a:higher}…")),
    Q(2.2, tag("S&P 500 · SHILLER CAPE"), head("Only one time {a:higher}…"), pause("GUESS THE YEAR"), timer(2)),
    S("@a December 1999.",
      tag("S&P 500 · SHILLER CAPE"),
      big("DEC 1999", color="red", at="a"),
      rows([("Today", "41", "amber"), ("Dec 1999", "44", "red")]),
      src="Shiller CAPE: 44.2 in Dec 1999, ~41 in Sep 2026"),
    S("So I did what this channel does.",
      head("So I did what this channel does.")),
    S("I took real euro data, going back to 1999, @a and I replayed the dot-com crash on the portfolio most Europeans own today.",
      timeline([(1999, "Euro\ndata", "amber"), (2000, "Dot-com\ncrash", "red"), (2008, "Financial\ncrisis", "red"),
                (2026, "Your\nportfolio", "green")]),
      stamp("REPLAYED", color="amber", angle=-6, at="a")),
    S("You'll see how long it took to get your money back, what the dollar did to euro investors, @a which safer alternatives actually helped, and which ones barely made a difference.",
      rows([("Time to get your money back", "?", "amber"), ("What the dollar did", "?", "amber")]),
      rows([("Which alternatives helped", "?", "amber")], at="a")),
    S("And at the end, I'll show you one number that matters more than any crash.",
      big("€??,???", color="amber", size=170),
      sub("One number that matters {a:more than any crash}")),
    S("This is The AI Bubble in Europe.",
      head("THE AI BUBBLE {a:IN EUROPE}", size=118),
      sub("I replayed the dot-com crash on your world ETF")),

    # ================================================================ CHAPTER 1
    S("Chapter one. What you really own.", *chapter(1)),
    S("The most popular index for European ETF investors is the M S C I World.",
      tag("EUROPE'S FAVOURITE INDEX"),
      big("MSCI WORLD", color="amber", size=170)),
    S("It holds @a over thirteen hundred companies, @b in twenty-three developed countries.",
      tag("MSCI WORLD"),
      count(1300, "{:,.0f}+", size=190, at="a"),
      sub("companies in {a:23 countries}", at="b")),
    S("Together with its bigger cousins, the All-World and A C W I funds, it sits behind millions of savings plans, from Germany to Spain, from France to the Netherlands.",
      chips(["MSCI World", "All-World", "ACWI"]),
      chips(["Germany", "Spain", "France", "Netherlands", "Italy"], delay=1.2)),
    S("European ETFs now hold a record @a three point nine seven trillion dollars.",
      tag("EUROPEAN ETF MARKET · AUG 2026"),
      count(3.97, "${:.2f}T", color="amber", size=190, at="a"),
      stamp("RECORD", color="green", angle=-8),
      src="ETFGI, European ETF industry, end of August 2026"),
    S("@b And this year alone, investors added three hundred and eighty one billion more.",
      tag("EUROPEAN ETF MARKET · AUG 2026"),
      count(381, "+${:,.0f}B", color="green", size=190, at="b"),
      sub("net inflows, this year"), src="ETFGI, European ETF industry, end of August 2026"),
    S("Most of that money flows into the same handful of global index funds.",
      head("Same handful of {a:global funds}.")),
    S("So what's actually inside them matters to a lot of people.",
      head("So what's {a:inside}?", size=110)),
    S("That sounds diversified.",
      count(1300, "{:,.0f}+", size=170, frm=1300),
      sub("companies… sounds diversified")),
    S("But the index is weighted by size.",
      head("Weighted by {a:size}.", size=110)),
    S("The bigger a company, the more of your money goes into it.",
      bars([("Giant", 90, "more €", "amber"), ("Medium", 35, "less €", "slate"), ("Small", 8, "tiny", "slate")], maxv=100)),
    S("So let's follow one hundred euros into a world ETF today.",
      tag("€100 INTO A WORLD ETF"),
      count(100, "€{:.0f}", color="amber", size=200)),
    S("Every square is one euro.",
      tag("€100 INTO A WORLD ETF"),
      waffle([(100, "slate", "")])),
    S("More than @a seventy of them go to American companies.",
      tag("€100 INTO A WORLD ETF"),
      waffle([(71, "amber", "USA"), (29, "slate", "Rest of the world")], at="a"),
      src="MSCI World country weights, end of August 2026"),
    Q(1.8, tag("€100 INTO A WORLD ETF"), donut(71, "USA"), src="MSCI World country weights, end of August 2026"),
    S("And about @a twenty-seven euros go to just ten companies.",
      tag("€100 INTO A WORLD ETF"),
      waffle([(27, "red", "Top 10 companies"), (44, "amber", "Rest of USA"), (29, "slate", "Rest of the world")], at="a"),
      src="MSCI World top-10 weight ≈ 27%, August 2026"),
    S("Put differently: if those ten companies fell by half tomorrow, @a your whole world ETF would lose about thirteen percent, even if every other company on Earth stood perfectly still.",
      tag("IF THE TOP 10 FELL 50%"),
      count(-13.5, "{:.1f}%", color="red", at="a"),
      sub("…with every other company {a:unchanged}")),
    S("Who are they?",
      tag("THE TOP 10"),
      head("Who are {a:they}?", size=110)),
    S("@a Nvidia, Microsoft, Apple, Broadcom, Amazon, Alphabet, Meta.",
      tag("THE TOP 10"),
      chips(GIANTS, at="a")),
    S("The names behind almost every AI headline.",
      chips(GIANTS),
      stamp("AI", color="amber", size=120, angle=-8)),
    S("Nvidia alone is valued at around @a five point three trillion dollars.",
      tag("NVIDIA"),
      count(5.3, "${:.1f}T", color="amber", at="a")),
    S("That's more than every listed company in Germany put together.",
      versus(("Nvidia", "${:.1f}T", 5.3, "amber", 5.3), ("All of Germany", "{}", 0, "slate", 0),
             notes=("one company", "every listed company")),
      head("{a:Nvidia} > Germany", size=72)),
    S("And this concentration is new.",
      head("This concentration is {r:new}.")),
    S("Not long ago, the five biggest companies were around @a six percent of the world index.",
      tag("TOP 5 WEIGHT IN MSCI WORLD"),
      bars([("Before", 6, "6%", "slate")], maxv=22, at="a")),
    S("@b By the end of 2024, they were close to twenty percent.",
      tag("TOP 5 WEIGHT IN MSCI WORLD"),
      bars([("Before", 6, "6%", "slate")], maxv=22),
      bars([("End of 2024", 20, "≈20%", "red")], maxv=22, at="b"),
      stamp("×3", color="red", size=110, angle=-8),
      src="MSCI World, weight of the 5 largest constituents"),
    S("The technology sector went from about a tenth of the index to @a more than a quarter in ten years.",
      tag("TECH SECTOR IN MSCI WORLD"),
      donut(10, "10 years ago", color="slate", slot="d", until="a"),
      donut(26, "today", color="amber", slot="d", at="a")),
    S("To be clear, none of this is a conspiracy.",
      stamp("NOT A CONSPIRACY", color="green", angle=-5)),
    S("It's simply how market cap indices work.",
      head("It's how {a:market-cap indices} work.")),
    S("When a company grows, you automatically own more of it.",
      head("Company grows →"),
      head("{a:you own more}", delay=0.6)),
    S("And it's exactly why world ETFs did so well over the last decade.",
      tag("€10,000 · LAST DECADE"),
      chart([dict(x=X, y=WORLD, upto=2026.7, frm=2015, color="green", end_label=True)], draw="s",
            xr=(2015, 2027), yr=(10000, 50000), xticks=[2016, 2020, 2024], yticks=[(20000, "€20k"), (40000, "€40k")], h=360),
      src=SRC_WORLD),
    S("You rode the winners all the way up.",
      head("You rode the {g:winners} all the way up.")),
    S("Think about what that means.",
      head("Think about it.", size=110)),
    S("You never had to pick Nvidia.",
      chips(["Nvidia"], strike=True),
      sub("You never picked it")),
    S("The index picked it for you, @a and kept adding more as the price went up.",
      head("The index picked it {a:for you}"),
      bars([("Weight", 2, "2%", "slate"), ("Weight", 5, "5%", "amber"), ("Weight", 8, "8%", "red")], maxv=10, at="a")),
    S("There's no rule in a market cap index that says: this is getting too expensive, let's take some money off the table.",
      head("“Too expensive?”"),
      stamp("NO SUCH RULE", angle=-6)),
    S("@a Price goes up, weight goes up.",
      head("Price ↑", slot="p", at="a"),
      head("Weight ↑", delay=0.0, at="a")),
    S("That's it.",
      head("That's {a:it}.", size=120)),
    S("But it works in both directions.",
      head("It works in {a:both directions}.")),
    S("@a When a giant falls, it falls with your money inside it.",
      head("When a giant falls…", at="a"),
      sub("…it falls {r:with your money inside}.")),
    S("The E C B economists put it bluntly.",
      pill("ECB WARNING"),
      head("They put it {a:bluntly}.")),
    S("Looking at past technology revolutions, @a a correction is likely, and euro area households would feel it mostly through their funds.",
      pill("ECB WARNING"),
      head("“A correction is {r:likely}.”", at="a"),
      sub("Felt mostly through funds and ETFs"), src=SRC_ECB),
    S("Quick question before we go back in time.",
      tag("QUESTION 1/3", color="amber"),
      head("Quick question.", size=110)),
    S("In the year 2000, at the peak of the dot-com bubble, what share of the S and P five hundred did its ten largest companies make up?",
      tag("QUESTION 1/3", color="amber"), Q1H, Q1),
    Q(3.2, tag("QUESTION 1/3", color="amber"), Q1H, Q1, pause(), timer(3)),
    S("Fifteen, twenty-six, or forty percent? Think about it. @r It was about twenty-six percent.",
      tag("QUESTION 1/3", color="amber"), Q1H, Q1),
    S("Today?",
      tag("TOP 10 SHARE OF THE S&P 500"),
      bars([("2000", 26, "26%", "slate")], maxv=44)),
    S("It's close to @a forty.",
      tag("TOP 10 SHARE OF THE S&P 500"),
      bars([("2000", 26, "26%", "slate")], maxv=44),
      bars([("2026", 40, "≈40%", "red")], maxv=44, at="a")),
    S("@b Higher than at the peak of the dot-com bubble.",
      tag("TOP 10 SHARE OF THE S&P 500"),
      bars([("2000", 26, "26%", "slate"), ("2026", 40, "≈40%", "red")], maxv=44),
      stamp("HIGHER THAN 2000", at="b"),
      src="S&P 500 top-10 weight, 2000 vs 2026"),

    # ================================================================ CHAPTER 2
    S("Chapter two. We've been here before.", *chapter(2)),
    S("Twice, in fact.",
      timeline([(1989, "Japan", "red"), (2000, "Dot-com", "red"), (2026, "AI?", "amber")]),
      stamp("TWICE", color="amber", angle=-6)),
    S("Let's start with the one most people forget.",
      timeline([(1989, "Japan", "red"), (2000, "Dot-com", "red"), (2026, "AI?", "amber")]),
      head("The one people {a:forget}")),
    S("December 1989.",
      tag("FLASHBACK"),
      big("DEC 1989", color="amber")),
    S("Japan is the hottest stock market on Earth.",
      tag("DECEMBER 1989"),
      head("Japan is the {a:hottest market} on Earth.")),
    S("Banks, real estate, electronics.",
      chips(["Banks", "Real estate", "Electronics"])),
    S("Everyone wants in.",
      chips(["Banks", "Real estate", "Electronics"]),
      stamp("EVERYONE WANTS IN", color="amber", angle=-6)),
    S("At its peak, Japan made up @a around forty-two percent of the entire global stock market.",
      tag("JAPAN, SHARE OF GLOBAL STOCKS"),
      donut(42, "of global stocks", color="red", at="a"),
      src="justETF, Japan's peak weight in global equities, 1989"),
    S("Japanese stocks traded at around sixty times their earnings.",
      tag("JAPAN · 1989"),
      count(60, "{:.0f}×", color="red"),
      sub("price / earnings")),
    S("People joked that the land under the Imperial Palace in Tokyo was worth more than all the real estate in California.",
      versus(("Imperial Palace", "{}", 0, "amber", 0), ("All of California", "{}", 0, "slate", 0),
             notes=("Tokyo, 1989", "all real estate")),
      head("Worth {a:more}?!", size=72)),
    S("Bigger than the United States.",
      tag("1989"),
      bars([("Japan", 42, "≈42%", "red"), ("USA", 30, "smaller", "slate")], maxv=46)),
    S("If you bought the world in 1989, you mostly bought Japan.",
      head("Buy the world = {a:buy Japan}")),
    S("The Nikkei closed that year at almost thirty-nine thousand points.",
      tag("NIKKEI 225"),
      count(38916, "{:,.0f}", color="amber", size=170)),
    S("@a It would take thirty-four years, until February 2024, to see that level again.",
      tag("NIKKEI 225 · YEAR-END"),
      chart([dict(x=NIKKEI_X, y=NIKKEI, upto=2024, color="red", end_label=False)], draw="a", h=330, **NIKKEI_AXES),
      count(34, "{:.0f} YEARS", color="red", size=130, at="a"),
      src="Nikkei 225: 38,916 on 29 Dec 1989; surpassed in Feb 2024"),
    S("Today Japan is around @a six percent of the world index.",
      tag("JAPAN IN THE WORLD INDEX"),
      donut(42, "1989", color="red", slot="j", until="a"),
      donut(6, "today", color="amber", slot="j", at="a")),
    S("But here's the part almost nobody tells you.",
      pill("PLOT TWIST"),
      head("The part {a:nobody} tells you")),
    S("A world index investor in 1989 was not ruined.",
      stamp("NOT RUINED", color="green", angle=-6)),
    S("As Japan shrank, the index automatically shifted toward everything else.",
      waffle([(42, "red", "Japan, 1989"), (58, "slate", "Everything else")]),
      sub("…and the index {a:shifted}")),
    S("@a In dollars, the world index was back to its 1989 level within about four years.",
      head("World index, back to 1989 level:", size=64),
      count(4, "≈{:.0f} YEARS", color="green", at="a"),
      src="MSCI World in USD, 1989 → 1993"),
    S("That's the self-cleaning feature of a market cap index.",
      head("The {a:self-cleaning} index")),
    S("It concentrates into bubbles, @a but it also lets the losers shrink and the next winners grow.",
      rows([("Concentrates into bubbles", "✕", "red")]),
      rows([("Lets losers shrink", "✓", "green"), ("Lets winners grow", "✓", "green")], at="a")),
    S("Now the second time.",
      timeline([(1989, "Japan", "slate"), (2000, "Dot-com", "red"), (2026, "AI?", "amber")]),
      head("The {a:second} time")),
    S("March 2000.",
      tag("FLASHBACK"),
      big("MAR 2000", color="amber")),
    S("The internet changes everything, and investors pay any price for it.",
      head("The internet changes {a:everything}."),
      sub("Investors pay {r:any price}.")),
    S("The top ten companies are about @a twenty-six percent of the S and P five hundred.",
      tag("MARCH 2000"),
      count(26, "{:.0f}%", color="amber", at="a"),
      sub("top 10 share of the S&P 500")),
    S("@b Valuations hit forty-four times earnings, the highest ever recorded.",
      tag("SHILLER CAPE · MARCH 2000"),
      count(44, "{:.0f}", color="red", at="b"),
      stamp("ALL-TIME HIGH", angle=-6)),
    S("For a moment in March 2000, @a Cisco, a company that makes network equipment, was the most valuable company in the world.",
      tag("WORLD'S MOST VALUABLE COMPANY"),
      big("CISCO", color="amber", at="a"),
      sub("…it makes {a:network equipment}")),
    S("Companies with no profits went public and doubled on their first day.",
      rows([("Profits", "€0", "red"), ("Day-one move", "×2", "green")])),
    S("If it had dot com in the name, people bought it.",
      big(".COM", color="amber", size=220),
      stamp("BUY!", color="green", angle=-10)),
    S("Then it breaks.",
      stamp("THEN IT BREAKS", size=100, angle=-5)),
    S("The Nasdaq one hundred falls @a more than eighty percent.",
      tag("NASDAQ-100 · 2000 → 2002"),
      count(-80, "{:.0f}%+", color="red", at="a")),
    S("It needs @a more than fifteen years to get back to its peak.",
      tag("NASDAQ-100 · BACK TO THE PEAK"),
      count(15, "{:.0f}+ YEARS", color="red", at="a"),
      src="Nasdaq-100 peak 4,704.73 on 27 Mar 2000"),
    S("And no, Europe was not a safe place to hide.",
      head("Europe was {r:not} a safe place to hide.")),
    S("Telecom stocks were the European version of the bubble.",
      chips(["Telecoms", "Media", "Tech"]),
      sub("Europe's own {a:bubble}")),
    S("The Euro Stoxx fifty lost @a about two thirds of its value from 2000 to 2003.",
      tag("EURO STOXX 50 · 2000 → 2003"),
      count(-66, "{:.0f}%", color="red", at="a"),
      src="Euro Stoxx 50: ≈5,464 (Mar 2000) → ≈1,850 (Mar 2003)"),
    S("Germany had its own story.",
      tag("GERMANY"),
      head("Germany's {a:own story}")),
    S("Deutsche Telekom was sold to ordinary families as the people's share.",
      tag("DEUTSCHE TELEKOM"),
      big("“VOLKSAKTIE”", color="amber", size=150),
      sub("the people's share")),
    S("@a At the peak in March 2000, it traded above one hundred euros.",
      tag("DEUTSCHE TELEKOM"),
      count(103, "€{:.0f}", color="amber", at="a"),
      sub("March 2000")),
    S("Two years later, @a it was below ten.",
      tag("DEUTSCHE TELEKOM"),
      strike("€103", at="a"),
      big("< €10", color="red", size=170, at="a"), src="Deutsche Telekom share price, Xetra"),
    S("Millions of first-time investors lost about ninety percent, and a whole generation of Germans swore off the stock market.",
      count(-90, "{:.0f}%", color="red", size=170),
      sub("A generation {r:swore off} stocks")),
    S("That's the hidden cost of a bubble.",
      head("The {a:hidden cost} of a bubble")),
    S("Not just the money.",
      head("Not just the money.")),
    S("The people who never come back.",
      head("The people who {r:never come back}.")),
    S("So let's put then and now side by side.",
      tag("THEN VS NOW"), table(["", "2000", "2026"], [])),
    S("Share of the top ten in the S and P five hundred: @a about twenty-six percent then, close to forty now.",
      tag("THEN VS NOW"), table(["", "2000", "2026"], TBL[:1], at="a")),
    S("Valuations: @a forty-four then, around forty-one now.",
      tag("THEN VS NOW"), table(["", "2000", "2026"], TBL[:2], at="a")),
    S("And the US share of the world index: @a roughly half back then.",
      tag("THEN VS NOW"), table(["", "2000", "2026"], TBL[:2] + [("USA in MSCI World", "≈50%", "")], at="a")),
    S("More than seventy percent today.",
      tag("THEN VS NOW"), table(["", "2000", "2026"], TBL)),
    S("On paper, today looks just as stretched, and more concentrated.",
      tag("THEN VS NOW"), table(["", "2000", "2026"], TBL),
      stamp("MORE CONCENTRATED", angle=-5)),
    S("There is one big difference.",
      pill("ONE BIG DIFFERENCE")),
    S("Today's giants make enormous profits.",
      pill("ONE BIG DIFFERENCE"),
      head("Today's giants make {g:enormous profits}.")),
    S("In 2000, plenty of internet darlings had no earnings at all.",
      versus(("2000 darlings", "€{:.0f}", 0, "red", 0), ("2026 giants", "{}", 0, "green", 0),
             notes=("earnings", "huge profits"))),
    S("But profitable doesn't mean cheap.",
      head("Profitable ≠ {r:cheap}", size=110)),
    S("@a Cisco was very profitable in 2000.",
      tag("CISCO · 2000"),
      big("PROFITABLE", color="green", size=150, at="a")),
    S("Its share price still fell by more than eighty percent.",
      tag("CISCO · 2000 → 2002"),
      count(-80, "{:.0f}%+", color="red")),
    S("A great company can still be a bad investment at the wrong price.",
      head("Great company. {r:Bad investment.}", size=72),
      stamp("WRONG PRICE", angle=-6)),

    # ================================================================ CHAPTER 3
    S("Chapter three. The replay.", *chapter(3)),
    S("Here's the setup.",
      tag("THE SETUP"),
      head("The {a:setup}", size=110)),
    S("Ten thousand euros into world stocks, on the last day of 1999.",
      tag("THE SETUP"),
      count(10000, "€{:,.0f}", color="amber", size=190),
      sub("31 December 1999"), src=SRC_WORLD),
    S("Right at the top.",
      count(10000, "€{:,.0f}", color="amber", size=190, frm=10000),
      stamp("RIGHT AT THE TOP", angle=-6)),
    S("M S C I World, dividends reinvested, measured in euros, after a zero point two percent yearly fee.",
      tag("THE RULES"),
      rows([("Index", "MSCI World", "white"), ("Currency", "EUR", "white"),
            ("Dividends", "reinvested", "white"), ("Fees", "0.2% / year", "white")]), src=SRC_WORLD),
    S("No cherry picking.",
      stamp("NO CHERRY PICKING", color="green", angle=-6)),
    S("Question two.",
      tag("QUESTION 2/3", color="amber"),
      head("Question {a:two}.", size=110)),
    S("By the end of 2002, how much of your ten thousand euros was left?",
      tag("QUESTION 2/3", color="amber"), Q2H, Q2, src=SRC_WORLD),
    Q(3.2, tag("QUESTION 2/3", color="amber"), Q2H, Q2, pause(), timer(3), src=SRC_WORLD),
    S("Eight thousand nine hundred, seven thousand two hundred, or five thousand five hundred? @r Five thousand five hundred.",
      tag("QUESTION 2/3", color="amber"), Q2H, Q2, src=SRC_WORLD),
    S("@a Forty-five percent gone in three years.",
      count(-45, "{:.0f}%", color="red", size=150, at="a"),
      chart([world_series(2002)], draw="a", h=360, **CRASH_AXES), src=SRC_WORLD),
    S("And remember, this is the whole world index.",
      chart([world_series(2002)], **CRASH_AXES),
      stamp("WHOLE WORLD", angle=-5), src=SRC_WORLD),
    S("Not a tech fund.",
      chart([world_series(2002)], **CRASH_AXES),
      head("Not a {a:tech fund}."), src=SRC_WORLD),
    S("Then the recovery starts.",
      tag("THE RECOVERY"),
      chart([world_series(2003, frm=2002)], draw="s", **CRASH_AXES), src=SRC_WORLD),
    S("2003, 2004, 2005.",
      tag("THE RECOVERY"),
      chart([world_series(2005, frm=2003)], draw="s", **CRASH_AXES), src=SRC_WORLD),
    S("By the end of 2006, you're at @a eight thousand seven hundred.",
      tag("THE RECOVERY"),
      chart([world_series(2006, frm=2005)], draw="s", **CRASH_AXES),
      sub("End of 2006: {a:€8,749}", at="a"), src=SRC_WORLD),
    S("Almost there.",
      chart([world_series(2006)], **CRASH_AXES),
      stamp("ALMOST THERE", color="green", angle=-6), src=SRC_WORLD),
    S("And then, @a 2008.",
      chart([world_series(2008, frm=2006)], draw="a", **CRASH_AXES),
      stamp("2008", size=110, at="a"), src=SRC_WORLD),
    S("By the end of 2008, your portfolio is worth @a five thousand three hundred euros.",
      count(5327, "€{:,.0f}", color="red", frm=8749, size=150, at="a"),
      chart([world_series(2008)], h=360, **CRASH_AXES), src=SRC_WORLD),
    S("Read that again.",
      count(5327, "€{:,.0f}", color="red", frm=5327, size=150),
      head("Read that {a:again}.")),
    S("Nine years in, you have @a less money than at the bottom of the dot-com crash.",
      tag("NINE YEARS IN"),
      versus(("Bottom 2002", "€{:,.0f}", 5515, "red", 10000), ("Bottom 2008", "€{:,.0f}", 5327, "red", 10000), at="a"),
      src=SRC_WORLD),
    S("So when are you finally back above ten thousand euros?",
      QRH, QR, src=SRC_WORLD),
    Q(3.2, QRH, QR, pause(), timer(3), src=SRC_WORLD),
    S("@a In 2013.",
      QRH, QR, src=SRC_WORLD),
    S("@a Thirteen years.",
      chart([world_series(2013, frm=2008)], draw="a", **CRASH_AXES),
      count(13, "{:.0f} YEARS", color="red", size=140, at="a"), src=SRC_WORLD),
    S("Thirteen years of doing everything right, and having nothing to show for it.",
      count(13, "{:.0f} YEARS", color="red", size=140, frm=13),
      sub("of doing {a:everything right}…"),
      stamp("NOTHING TO SHOW", angle=-6)),
    S("If you started investing in your thirties, you'd be close to fifty before you saw a profit.",
      versus(("You start at", "{:.0f}", 35, "amber", 25), ("First profit at", "{:.0f}", 48, "red", 35))),
    S("And it wasn't a quiet thirteen years.",
      head("Not a {r:quiet} 13 years.")),
    S("You lived through two crashes of almost fifty percent each.",
      chart([world_series(2013)], **CRASH_AXES),
      stamp("TWO CRASHES", angle=-6), src=SRC_WORLD),
    S("@a Your bank advisor, the news, your friends, everyone told you stocks were dead.",
      chips(["Bank advisor", "The news", "Your friends"], at="a"),
      head("“Stocks are {r:dead}.”", delay=1.6)),
    S("By the way, if you saw my short on this, the start date there was January 2001, and the answer was twelve years.",
      tag("FROM THE SHORTS"),
      rows([("Start Jan 2001", "12 years", "amber")])),
    S("Starting at the very top makes it one year worse.",
      tag("FROM THE SHORTS"),
      rows([("Start Jan 2001", "12 years", "amber"), ("Start Dec 1999 (the top)", "13 years", "red")])),
    S("Now, the other side of the story.",
      pill("THE OTHER SIDE")),
    S("That same ten thousand euros, invested at the worst possible moment, @a is worth about forty-six thousand euros today.",
      tag("31 DEC 1999 → AUGUST 2026"),
      chart([world_series(2026.7, frm=2013)], draw="s", h=300, **WORLD_AXES),
      count(46032, "€{:,.0f}", color="green", frm=10000, size=140, at="a"), src=SRC_WORLD),
    S("That's about @a five point nine percent a year, for almost twenty-seven years.",
      tag("31 DEC 1999 → AUGUST 2026"),
      count(5.9, "{:.1f}% / YEAR", color="green", size=160, at="a"), src=SRC_WORLD),
    S("After the dot-com crash, after 2008, after Covid, after 2022.",
      timeline([(2000, "Dot-com", "red"), (2008, "GFC", "red"), (2020, "Covid", "red"), (2022, "Inflation", "red")])),
    S("And before you say, yes, but inflation: prices in the euro area rose about seventy-six percent from 1999 to 2025.",
      tag("ADJUSTED FOR INFLATION"),
      count(76, "+{:.0f}%", color="amber", size=170),
      sub("euro area prices, 1999 → 2025"), src="Euro area HICP (ECB), Dec 1999 – Dec 2025"),
    S("@a So in today's money, your ten thousand euros became roughly two and a half times as much.",
      tag("ADJUSTED FOR INFLATION"),
      count(2.5, "×{:.1f}", color="green", size=200, at="a"),
      sub("real growth of your €10,000")),
    S("Still a real gain.",
      stamp("REAL GAIN", color="green", angle=-6)),
    S("And the crashes kept coming.",
      head("The crashes kept {r:coming}.")),
    S("In 2020, Covid sent markets down by a third in a few weeks.",
      tag("2020 · COVID"),
      count(-33, "{:.0f}%", color="red", size=170),
      sub("in a few {a:weeks}")),
    S("@a In 2022, world stocks lost almost thirteen percent in euros, while bonds fell too.",
      tag("2022"),
      bars([("World stocks (EUR)", 12.8, "−12.8%", "red"), ("Euro govt bonds", 18.4, "−18.4%", "red")], maxv=22, at="a"),
      src=SRC_WORLD),
    S("Each one felt like the end of the world at the time.",
      stamp("END OF THE WORLD?", angle=-6)),
    S("@a On this chart, they're small dents.",
      tag("31 DEC 1999 → AUGUST 2026"),
      chart([world_series(2026.7)], draw="a", **WORLD_AXES),
      sub("Here: {a:small dents}."), src=SRC_WORLD),
    S("So buying at the top did not ruin you.",
      head("Buying at the top {g:didn't ruin you}.")),
    S("@a Selling at the bottom would have.",
      head("Buying at the top {g:didn't ruin you}."),
      head("Selling at the bottom {r:would have}.", at="a")),
    S("But most of you don't invest a lump sum on one day.",
      strike("LUMP SUM", size=150)),
    S("You invest every month.",
      tag("THE SAVINGS PLAN"),
      head("You invest {a:every month}.")),
    S("So let's replay that too.",
      stamp("REPLAY #2", color="amber", angle=-6)),
    S("Three hundred euros a month, starting in January 2000.",
      tag("THE SAVINGS PLAN"),
      count(300, "€{:,.0f} / MONTH", size=150),
      sub("from January 2000")),
    S("Straight into the crash.",
      count(300, "€{:,.0f} / MONTH", size=150, frm=300),
      stamp("INTO THE CRASH", angle=-6)),
    S("End of 2002.",
      tag("END OF 2002"),
      big("2002", color="amber")),
    S("You've put in @a ten thousand eight hundred euros.",
      tag("END OF 2002"),
      versus(("Put in", "€{:,.0f}", 10800, "white", 0), ("Worth", "{}", 0, "slate", 0), at="a")),
    S("@b It's worth seven thousand two hundred.",
      tag("END OF 2002"),
      versus(("Put in", "€{:,.0f}", 10800, "white", 10800), ("Worth", "€{:,.0f}", 7265, "red", 10800), at="b"),
      src=SRC_PLAN),
    S("End of 2008, after nine years of saving: @a thirty-two thousand four hundred in, @b twenty-three thousand four hundred left.",
      tag("END OF 2008"),
      versus(("Put in", "€{:,.0f}", 32400, "white", 0), ("Worth", "{}", 0, "slate", 0), slot="v", at="a", until="b"),
      versus(("Put in", "€{:,.0f}", 32400, "white", 32400), ("Worth", "€{:,.0f}", 23373, "red", 32400), slot="v", at="b"),
      src=SRC_PLAN),
    S("That's the moment most people quit.",
      stamp("MOST PEOPLE QUIT", size=96, angle=-6)),
    S("But those were the months when every three hundred euros bought the most shares.",
      bars([("€300 in 2007", 3, "3 shares", "slate"), ("€300 in 2009", 6, "6 shares", "green")], maxv=7),
      sub("illustrative")),
    S("@a The crash years were your best buying years.",
      head("Crash years = {g:best buying years}", at="a")),
    S("Today, you've put in ninety-six thousand euros.",
      tag("€300 / MONTH · JAN 2000 → AUG 2026"),
      chart([dict(x=PLAN_X, y=PLAN_PAID, upto=2026.7, color="slate", end_label=True)],
            draw="s", xr=(1999, 2027), yr=(0, 450000), xticks=[2000, 2010, 2020],
            yticks=[(100000, "€100k"), (400000, "€400k")], h=330), src=SRC_PLAN),
    S("@a The plan is worth about four hundred and sixteen thousand.",
      tag("€300 / MONTH · JAN 2000 → AUG 2026"),
      chart([dict(x=PLAN_X, y=PLAN_PAID, upto=2026.7, color="slate", end_label=True),
             dict(x=PLAN_X, y=PLAN_V, upto=2026.7, color="green", end_label=True)],
            draw="a", xr=(1999, 2027), yr=(0, 450000), xticks=[2000, 2010, 2020],
            yticks=[(100000, "€100k"), (400000, "€400k")], h=300),
      count(415875, "€{:,.0f}", color="green", size=130, at="a"), src=SRC_PLAN),
    S("The crash didn't hurt the monthly saver.",
      head("The crash {g:didn't hurt} the monthly saver.")),
    S("It paid them.",
      stamp("IT PAID THEM", color="green", size=100, angle=-6)),
    S("But only if they kept going.",
      head("…if they {a:kept going}.", size=100)),

    # ================================================================ CHAPTER 4
    S("Chapter four. The currency trap.", *chapter(4)),
    S("There's a layer most European investors completely forget.",
      head("The layer everyone {a:forgets}…")),
    S("The dollar.",
      big("$", color="amber", size=320)),
    S("More than seventy percent of your world ETF is priced in dollars.",
      donut(71, "in dollars", color="amber")),
    S("@a When the dollar falls against the euro, you lose money, even if American stocks don't move at all.",
      head("Dollar ↓ vs euro", at="a"),
      head("= {r:you lose}", delay=0.0, at="a"),
      sub("even if US stocks don't move")),
    S("Here's a simple example.",
      pill("EXAMPLE")),
    S("Say an American stock stays exactly flat in dollars for a year.",
      pill("EXAMPLE"),
      rows([("Stock in USD", "0%", "white")])),
    S("@a But the euro rises ten percent.",
      pill("EXAMPLE"),
      rows([("Stock in USD", "0%", "white")]),
      rows([("Euro vs dollar", "+10%", "amber")], at="a")),
    S("In euros, you just lost about nine percent.",
      pill("EXAMPLE"),
      rows([("Stock in USD", "0%", "white"), ("Euro vs dollar", "+10%", "amber")]),
      rows([("Your result in EUR", "≈ −9%", "red")])),
    S("On a stock that didn't move.",
      count(-9, "{:.0f}%", color="red", size=200),
      sub("on a stock that {a:didn't move}")),
    S("And here's a very common misunderstanding.",
      pill("COMMON MISTAKE")),
    S("Many people buy the euro listed version of their ETF and think the currency risk is gone.",
      pill("COMMON MISTAKE"),
      head("Bought it in euros = {g:no currency risk}?", size=66)),
    S("@a It isn't.",
      pill("COMMON MISTAKE"),
      head("Bought it in euros = {g:no currency risk}?", size=66),
      stamp("WRONG", size=130, at="a")),
    S("What matters is not the currency you pay with.",
      strike("YOUR CURRENCY", size=130)),
    S("It's the currency the underlying companies are priced in.",
      head("It's the {a:companies'} currency.")),
    S("@a Apple is a dollar company, whether you buy it in Frankfurt, Milan, or New York.",
      chips(["Frankfurt", "Milan", "New York"], at="a"),
      big("= $", color="amber", size=160)),
    S("And in the dot-com crash, that's exactly what happened.",
      tag("EUR / USD · YEAR-END"),
      chart([dict(x=EURUSD_X, y=EURUSD, upto=2001, color="amber", end_label=False)], draw="s", h=360, **FX_AXES),
      src="ECB euro reference rates"),
    S("In October 2000, one euro was worth just @a eighty-three cents.",
      tag("EUR / USD"),
      count(0.83, "${:.2f}", color="amber", size=190, at="a"),
      sub("October 2000"), src="ECB euro reference rates"),
    S("By the end of 2004, it was worth @b one dollar thirty-six.",
      tag("EUR / USD · YEAR-END"),
      chart([dict(x=EURUSD_X, y=EURUSD, upto=2004, frm=2001, color="amber", end_label=False)], draw="b", h=330, **FX_AXES),
      count(1.36, "${:.2f}", color="amber", size=130, frm=0.83, at="b"), src="ECB euro reference rates"),
    S("For a euro investor, that move alone wiped out @a almost forty percent of the value of every dollar asset.",
      tag("DOLLAR ASSETS, MEASURED IN EUR"),
      count(-39, "{:.0f}%", color="red", at="a"),
      sub("from the currency {a:alone}"), src="ECB euro reference rates"),
    S("Look at 2002.",
      tag("MSCI WORLD · 2002"),
      big("2002", color="amber")),
    S("World stocks lost @a about twenty percent in dollars.",
      tag("MSCI WORLD · 2002"),
      bars([("in USD", 20, "−20%", "slate")], maxv=40, at="a")),
    S("@b In euros, they lost thirty-three.",
      tag("MSCI WORLD · 2002"),
      bars([("in USD", 20, "−20%", "slate")], maxv=40),
      bars([("in EUR", 33, "−33%", "red")], maxv=40, at="b"),
      stamp("SECOND PUNCH", angle=-6), src="MSCI World net, 2002: −19.9% USD, −32.7% EUR"),
    S("Then 2008 did the opposite.",
      tag("MSCI WORLD · 2008"),
      head("2008 did the {g:opposite}.")),
    S("In the panic, investors ran to the dollar, and the dollar rose.",
      tag("MSCI WORLD · 2008"),
      big("$ ↑", color="green", size=220)),
    S("@a That cushioned the crash: minus forty-one percent in dollars, but minus thirty-seven in euros.",
      tag("MSCI WORLD · 2008"),
      bars([("in USD", 41, "−41%", "slate"), ("in EUR", 37, "−37%", "amber")], maxv=45, at="a"),
      stamp("AIRBAG", color="green", angle=-6),
      src="MSCI World net, 2008: −40.7% USD, −37.3% EUR"),
    S("And this isn't ancient history.",
      head("Not {a:ancient history}.")),
    S("In 2025, the dollar fell sharply against the euro.",
      tag("EUR / USD · YEAR-END"),
      chart([dict(x=EURUSD_X, y=EURUSD, upto=2025, frm=2023, color="amber", end_label=False)], draw="s", h=360, **FX_AXES),
      src="ECB euro reference rates"),
    S("@a World stocks gained around twenty percent in dollars, but only about seven percent for a euro investor.",
      tag("MSCI WORLD · 2025"),
      bars([("in USD", 21, "≈ +21%", "slate"), ("in EUR", 7.2, "≈ +7%", "amber")], maxv=25, at="a"),
      src=SRC_WORLD),
    S("So in a crash, the currency can be your airbag, @a or your second punch.",
      head("Your {g:airbag}…"),
      head("…or your {r:second punch}.", at="a")),
    S("And you don't get to choose in advance.",
      stamp("YOU DON'T CHOOSE", angle=-6)),
    S("Right now, the euro is around @a one dollar thirteen, its lowest level since May 2025, after both the Fed and the E C B raised rates in September.",
      tag("EUR / USD · TODAY"),
      count(1.13, "${:.2f}", color="amber", at="a"),
      chips(["Fed ↑", "ECB ↑ 2.50%"], delay=2.0),
      src="EUR/USD, late September 2026"),
    S("If the dollar falls back from here while US stocks fall too, euro investors get hit twice.",
      head("Dollar ↓ + US stocks ↓"),
      stamp("HIT TWICE", size=110, angle=-6)),
    S("Over the very long run, currency swings tend to wash out.",
      tag("EUR / USD · 1999 → 2026"),
      chart([dict(x=EURUSD_X, y=EURUSD, upto=2026.75, color="amber", end_label=False)], **FX_AXES),
      sub("Long run: {g:washes out}")),
    S("Over five or ten years, they can decide whether you made money or not.",
      head("5–10 years: {r:can decide everything}.")),
    S("Euro hedged share classes remove this risk.",
      tag("EUR-HEDGED ETFs"),
      rows([("Removes the second punch", "✓", "green")])),
    S("But they cost a bit more, and they also remove the airbag.",
      tag("EUR-HEDGED ETFs"),
      rows([("Removes the second punch", "✓", "green"), ("Costs a bit more", "✕", "red"), ("Removes the airbag", "✕", "red")])),
    S("@a There's no free lunch here.",
      stamp("NO FREE LUNCH", size=100, angle=-6, at="a")),

    # ================================================================ CHAPTER 5
    S("Chapter five. The stress test.", *chapter(5)),
    S("Now the real experiment.",
      pill("THE EXPERIMENT")),
    S("What would a crash do to the portfolios people actually hold today?",
      chips(["MSCI World", "All-World", "Equal Weight", "Europe only", "60/40"]),
      head("What would a crash {a:do}?", delay=1.0)),
    S("I split the world index into four buckets.",
      tag("TODAY'S MSCI WORLD, IN 4 BUCKETS"),
      big("4", color="amber", size=260)),
    S("The AI giants, @a about twenty-five percent. @b The rest of the US, about forty-six. @c Other developed markets, about twenty-nine. @d And for global funds, emerging markets.",
      tag("TODAY'S MSCI WORLD, IN 4 BUCKETS"),
      bars([("AI giants", 25, "25%", "red")], maxv=50, at="a"),
      bars([("Rest of USA", 46, "46%", "amber")], maxv=50, at="b"),
      bars([("Other developed", 29, "29%", "slate")], maxv=50, at="c"),
      bars([("Emerging (All-World)", 10.5, "≈10%", "slate")], maxv=50, at="d")),
    S("Why a separate bucket for the AI giants?",
      head("Why a separate bucket for the {r:AI giants}?", size=70)),
    S("Because if this is a bubble, that's where it is.",
      stamp("IF IT'S A BUBBLE, IT'S HERE", size=76, angle=-5)),
    S("The chips, the cloud, the data centres.",
      chips(["Chips", "Cloud", "Data centres"])),
    S("That's the money betting on AI.",
      chips(["Chips", "Cloud", "Data centres"]),
      head("= the {a:AI bet}")),
    S("Then I ran two scenarios, based on what really happened in past crashes.",
      versus(("Scenario A", "{}", 0, "amber", 0), ("Scenario B", "{}", 0, "red", 0),
             notes=("AI-only correction", "full dot-com replay"))),
    S("These are scenarios, not forecasts.",
      stamp("NOT A FORECAST", color="amber", angle=-6)),
    S("Scenario A: an AI-only correction. @a The AI giants fall fifty percent. @b The rest of the US falls ten. @c Other markets dip a little.",
      pill("SCENARIO A"),
      rows([("AI giants", "−50%", "red")], at="a"),
      rows([("Rest of USA", "−10%", "amber")], at="b"),
      rows([("Other developed / emerging", "−5% / −15%", "slate")], at="c")),
    S("Scenario B: a full dot-com replay. @a The AI giants lose seventy percent, @b and like in 2000, everything else falls hard too.",
      pill("SCENARIO B"),
      rows([("AI giants", "−70%", "red")], at="a"),
      rows([("Rest of USA / other developed", "−35% / −40%", "red"), ("Emerging", "−45%", "red")], at="b")),
    S("The maths is deliberately simple.",
      tag("THE METHOD"),
      head("weight × loss, {a:added up}", size=96)),
    S("For each portfolio, I multiplied its weight in each bucket by that bucket's loss, and added it all up.",
      tag("THE METHOD"),
      rows([("AI giants", "25% × −50%", "red"), ("Rest of USA", "46% × −10%", "amber"),
            ("Other developed", "29% × −5%", "slate"), ("MSCI World", "= −18.6%", "red")])),
    S("@a You could redo it on a napkin.",
      stamp("NAPKIN MATHS", color="green", angle=-6, at="a")),
    S("Scenario B isn't made up.",
      pill("SCENARIO B"),
      head("Not made up.", size=110)),
    S("From 2000 to 2002, the big tech names of that era lost seventy to ninety percent.",
      pill("SCENARIO B"),
      rows([("Big tech 2000 → 2002", "−70 to −90%", "red")])),
    S("The S and P five hundred lost about half.",
      pill("SCENARIO B"),
      rows([("Big tech 2000 → 2002", "−70 to −90%", "red"), ("S&P 500", "≈ −50%", "red")])),
    S("And as we saw, Europe lost about two thirds.",
      pill("SCENARIO B"),
      rows([("Big tech 2000 → 2002", "−70 to −90%", "red"), ("S&P 500", "≈ −50%", "red"), ("Euro Stoxx 50", "≈ −66%", "red")])),
    Q(3.2, tag("SCENARIO A · AI-ONLY CORRECTION", color="amber"), head("Which fund loses the {g:least}?", size=66),
      QX, pause(), timer(3)),
    S("Let's start with scenario A.",
      pill("SCENARIO A")),
    S("A plain M S C I World ETF loses @a about eighteen and a half percent.",
      pill("SCENARIO A"),
      bars(SCEN_A[:1], maxv=50, at="a"), src=SRC_SCEN),
    S("Now, many people think: I'll switch to an All-World fund, with emerging markets.",
      pill("SCENARIO A"),
      bars(SCEN_A[:1], maxv=50),
      head("“I'll switch to {a:All-World}!”", size=64), src=SRC_SCEN),
    S("@a That gets you to minus eighteen point two.",
      pill("SCENARIO A"),
      bars(SCEN_A[:1], maxv=50),
      bars(SCEN_A[1:2], maxv=50, at="a"), src=SRC_SCEN),
    S("Almost no difference.",
      pill("SCENARIO A"),
      bars(SCEN_A[:2], maxv=50),
      stamp("ALMOST NO DIFFERENCE", size=72, angle=-5), src=SRC_SCEN),
    S("Why?",
      head("Why?", size=160)),
    S("Because emerging markets are full of AI too.",
      head("Emerging markets are {a:full of AI} too.")),
    S("Taiwan and Korea are home to some of the biggest chipmakers on the planet.",
      chips(["TSMC", "Samsung", "SK Hynix"]),
      sub("Taiwan · Korea")),
    S("An equal weight world fund, where every company gets the same slice, @a loses only seven percent.",
      pill("SCENARIO A"),
      bars(SCEN_A[:2], maxv=50),
      bars(SCEN_A[2:3], maxv=50, at="a"), src=SRC_SCEN),
    S("Europe only: @a minus five.",
      pill("SCENARIO A"),
      bars(SCEN_A[:3], maxv=50),
      bars(SCEN_A[3:4], maxv=50, at="a"), src=SRC_SCEN),
    S("@b And a sixty forty portfolio, sixty percent world stocks and forty percent euro government bonds: minus nine.",
      pill("SCENARIO A"),
      bars(SCEN_A[:4], maxv=50),
      bars(SCEN_A[4:], maxv=50, at="b"), src=SRC_SCEN),
    S("Equal weight does well here for an obvious reason: the AI giants are just a handful of names out of more than thirteen hundred.",
      head("A handful out of {a:1,300+}"),
      waffle([(1, "red", "AI giants"), (99, "slate", "Everyone else")])),
    S("@a In an equal weight fund, they're less than one percent of your money.",
      tag("EQUAL WEIGHT FUND"),
      donut(0.6, "AI giants", color="red", fmt="<{:.0f}%".replace("{:.0f}", "1"), at="a")),
    S("But remember, Europe has its own giants too.",
      head("Europe has its {a:own giants}.")),
    S("A few companies like A S M L, S A P and Novo Nordisk drive a big part of European returns.",
      tag("EUROPE'S OWN GIANTS"),
      chips(["ASML", "SAP", "Novo Nordisk"])),
    S("Concentration isn't only an American thing.",
      chips(["ASML", "SAP", "Novo Nordisk"]),
      stamp("NOT ONLY AMERICAN", color="amber", angle=-6)),
    S("In an AI-only correction, the alternatives really work.",
      pill("SCENARIO A"),
      bars(SCEN_A, maxv=50),
      stamp("ALTERNATIVES WORK", color="green", angle=-6), src=SRC_SCEN),
    S("But now, scenario B.",
      pill("SCENARIO B"),
      head("Now, the {r:full replay}.", size=96)),
    S("M S C I World: @a minus forty-five percent.",
      pill("SCENARIO B"),
      bars(SCEN_B[:1], maxv=50, at="a"), src=SRC_SCEN),
    S("All-World: @b also minus forty-five.",
      pill("SCENARIO B"),
      bars(SCEN_B[:1], maxv=50),
      bars(SCEN_B[1:2], maxv=50, at="b"), src=SRC_SCEN),
    S("Equal weight: @a minus thirty-eight.",
      pill("SCENARIO B"),
      bars(SCEN_B[:2], maxv=50),
      bars(SCEN_B[2:3], maxv=50, at="a"), src=SRC_SCEN),
    S("Europe only: @b minus forty.",
      pill("SCENARIO B"),
      bars(SCEN_B[:3], maxv=50),
      bars(SCEN_B[3:4], maxv=50, at="b"), src=SRC_SCEN),
    S("And the sixty forty: @a minus twenty-four.",
      pill("SCENARIO B"),
      bars(SCEN_B[:4], maxv=50),
      bars(SCEN_B[4:], maxv=50, at="a"), src=SRC_SCEN),
    S("This is the uncomfortable result.",
      pill("SCENARIO B"),
      bars(SCEN_B, maxv=50),
      stamp("UNCOMFORTABLE", angle=-6), src=SRC_SCEN),
    S("In a real crash, switching from one stock index to another barely matters.",
      head("Swapping stock indices {r:barely matters}.")),
    S("@a The only thing that really changed the outcome was owning something that isn't stocks.",
      head("What changed the outcome:", at="a"),
      big("NOT STOCKS", color="green", size=150, at="a")),
    S("That doesn't make equal weight or All-World bad ideas.",
      chips(["Equal weight", "All-World"]),
      stamp("NOT BAD IDEAS", color="green", angle=-6)),
    S("They spread your bets more evenly.",
      head("They {a:spread} your bets.")),
    S("@a Since 2000, equal weight even edged out the standard world index, about seven point eight percent a year versus seven point five, in dollars.",
      tag("SINCE DEC 2000 · PER YEAR, USD"),
      bars([("MSCI World", 7.46, "7.46%", "slate"), ("MSCI World Equal Weight", 7.83, "7.83%", "amber")], maxv=9, at="a"),
      src="justETF index comparison, as of Jan 2026"),
    S("They're just not crash protection.",
      stamp("NOT CRASH PROTECTION", size=80, angle=-5)),
    S("And we don't have to guess.",
      head("We don't have to {a:guess}.")),
    S("Here's the real sixty forty, replayed from the end of 1999, with yearly rebalancing.",
      tag("€10,000 · 31 DEC 1999"),
      chart([world_series(2013, color="slate", end_label=False),
             dict(x=X, y=SIXTY40, upto=2013, color="green", end_label=False)], draw="s", **CRASH_AXES),
      src="60% MSCI World + 40% euro government bonds, rebalanced yearly, in EUR"),
    S("At the end of 2002, it was down @a twenty-one percent instead of forty-five.",
      tag("END OF 2002"),
      versus(("100% stocks", "{:.0f}%", -45, "red", 0), ("60/40", "{:.0f}%", -21, "amber", 0), at="a")),
    S("It was back above ten thousand euros in @a 2005.",
      tag("BACK ABOVE €10,000"),
      versus(("100% stocks", "{:.0f}", 2013, "red", 2013), ("60/40", "{:.0f}", 2005, "green", 2013), at="a")),
    S("Eight years earlier than the all-stock portfolio.",
      tag("BACK ABOVE €10,000"),
      versus(("100% stocks", "{:.0f}", 2013, "red", 2013), ("60/40", "{:.0f}", 2005, "green", 2013)),
      stamp("8 YEARS FASTER", color="green", angle=-6)),
    S("The price?",
      head("The {a:price}?", size=140)),
    S("Today it's worth about @a thirty-eight thousand six hundred, instead of forty-six thousand.",
      tag("AUGUST 2026"),
      versus(("100% stocks", "€{:,.0f}", 46032, "green", 10000), ("60/40", "€{:,.0f}", 38606, "amber", 10000), at="a")),
    S("Less growth, in exchange for much smaller holes.",
      rows([("Growth", "less", "amber"), ("Holes", "much smaller", "green")])),
    S("There's a hidden engine in that sixty forty: rebalancing.",
      tag("THE HIDDEN ENGINE"),
      big("REBALANCING", color="amber", size=140)),
    S("Every year it goes back to sixty percent stocks.",
      tag("THE HIDDEN ENGINE"),
      donut(60, "stocks, every year", color="amber")),
    S("@a So at the end of 2002 and 2008, it was forced to sell bonds and buy cheap stocks.",
      timeline([(2002, "Sell bonds\nbuy stocks", "green"), (2008, "Sell bonds\nbuy stocks", "green")], at="a")),
    S("Exactly when nobody wanted to.",
      stamp("WHEN NOBODY WANTED TO", size=76, angle=-5)),
    S("But there's a warning label.",
      pill("WARNING")),
    S("@a In 2022, euro government bonds lost about eighteen percent, in the same year stocks fell.",
      pill("WARNING"),
      count(-18, "{:.0f}%", color="red", at="a"),
      sub("euro govt bonds, 2022"), src="Euro area government bonds, all maturities, 2022"),
    S("Bonds protected you in 2000 and 2008, when interest rates fell.",
      rows([("2000 & 2008 · rates falling", "protected", "green")])),
    S("They don't protect you when inflation and rates are rising.",
      rows([("2000 & 2008 · rates falling", "protected", "green"), ("Inflation & rates rising", "didn't", "red")])),
    S("@a And inflation in the euro area is back above three percent.",
      tag("TODAY"),
      versus(("Euro area inflation", "{:.1f}%", 3.3, "red", 0), ("ECB deposit rate", "{:.2f}%", 2.50, "amber", 0), at="a"),
      src="Eurostat / ECB, September 2026"),
    S("And one more honest point.",
      pill("HONEST POINT")),
    S("Over the last decade, almost every one of these safer alternatives trailed the plain world index.",
      chips(["All-World", "Equal weight", "Europe", "60/40"]),
      sub("trailed the plain world index")),
    S("Protection always has a price.",
      stamp("PROTECTION HAS A PRICE", size=76, color="amber", angle=-5)),

    # ================================================================ CHAPTER 6
    S("Chapter six. What actually protected you.", *chapter(6)),
    S("So what really worked for European investors through the last two crashes?",
      head("What {a:really} worked?", size=110)),
    S("Three things.",
      big("3", color="amber", size=300)),
    S("@a And none of them is a clever ETF.",
      big("3", color="amber", size=300),
      stamp("NO CLEVER ETF", at="a")),
    S("Number one.",
      tag("1 / 3", color="amber"),
      big("#1", color="amber", size=240)),
    S("Matching your money to your time horizon.",
      tag("1 / 3", color="amber"),
      head("Match your money to your {a:time horizon}.")),
    S("Your world ETF needed thirteen years to recover from the dot-com top.",
      tag("1 / 3", color="amber"),
      count(13, "{:.0f} YEARS", color="red", size=170)),
    S("@a Money you need in the next five years has no business being one hundred percent in stocks.",
      tag("1 / 3", color="amber"),
      rows([("Money needed within 5 years", "not 100% stocks", "amber")], at="a")),
    S("Picture someone who's fifty-eight in 2026 and plans to retire at sixty-five.",
      timeline([(58, "Today\n2026", "white"), (65, "Planned\nretirement", "amber")])),
    S("If a dot-com style crash hits next year, a thirteen year recovery takes them to seventy-one.",
      timeline([(58, "Today\n2026", "white"), (65, "Planned\nretirement", "amber"), (71, "Back to\neven", "red")])),
    S("@a That's why the mix should change as the date gets closer.",
      head("The mix should change as the date {a:gets closer}.", size=70, at="a")),
    S("That's not about being scared.",
      strike("SCARED", size=170)),
    S("It's about not being forced to sell at the bottom because you need the money for a house, a car, or your retirement.",
      head("Never be {r:forced to sell}"),
      chips(["House", "Car", "Retirement"], delay=1.5)),
    S("The simplest tool for that isn't an ETF at all.",
      head("The simplest tool isn't an {a:ETF}…")),
    S("@a It's an emergency fund.",
      big("CASH BUFFER", color="green", size=150, at="a")),
    S("A few months of expenses in cash, so a broken car or a lost job never forces you to sell your ETF at minus forty percent.",
      big("CASH BUFFER", color="green", size=150),
      rows([("Broken car", "covered", "green"), ("Lost job", "covered", "green"), ("Sell at −40%?", "never", "green")])),
    S("Number two.",
      tag("2 / 3", color="amber"),
      big("#2", color="amber", size=240)),
    S("Keep buying.",
      tag("2 / 3", color="amber"),
      head("Keep {a:buying}.", size=130)),
    S("The monthly saver who kept going through 2002 and 2008 turned ninety-six thousand euros into about four hundred and sixteen thousand.",
      tag("2 / 3", color="amber"),
      versus(("Put in", "€{:,.0f}", 96000, "white", 0), ("Worth", "€{:,.0f}", 415875, "green", 0)), src=SRC_PLAN),
    S("@a The crashes were where most of that came from.",
      stamp("THANK THE CRASHES", color="green", angle=-6, at="a")),
    S("The practical way to do that is boring on purpose: a standing order on the same day every month, set up once, and then left alone.",
      head("Boring {a:on purpose}."),
      chips(["Same day", "Every month", "Automatic"], delay=1.2)),
    S("@a Most European brokers offer savings plans for free or close to it.",
      chips(["Same day", "Every month", "Automatic"]),
      sub("Savings plans: {g:free or close to it}", at="a")),
    S("Number three.",
      tag("3 / 3", color="amber"),
      big("#3", color="amber", size=240)),
    S("And this is the one that matters most.",
      tag("3 / 3", color="amber"),
      head("The one that matters {a:most}.")),
    S("Not selling.",
      stamp("NOT SELLING", size=130, color="green", angle=-6)),
    S("Let's meet two investors.",
      versus(("Investor A", "{}", 0, "amber", 0), ("Investor B", "{}", 0, "amber", 0))),
    S("Both put ten thousand euros into world stocks at the end of 1999.",
      versus(("Investor A", "€{:,.0f}", 10000, "white", 0), ("Investor B", "€{:,.0f}", 10000, "white", 0))),
    S("At the end of 2002, with forty-five percent gone, @a investor A panics.",
      tag("END OF 2002 · −45%"),
      versus(("Investor A", "€{:,.0f}", 5515, "red", 10000), ("Investor B", "€{:,.0f}", 5515, "red", 10000)),
      stamp("PANIC", size=110, at="a")),
    S("Sells everything.",
      tag("END OF 2002"),
      stamp("SOLD", size=150, angle=-8)),
    S("Puts the five thousand five hundred euros left into a savings account paying two percent a year.",
      tag("INVESTOR A"),
      rows([("Moved to savings", "€5,515", "white"), ("Interest", "2% / year", "amber")])),
    S("Investor B does nothing.",
      tag("INVESTOR B"),
      head("Does {g:nothing}.", size=120)),
    S("Doesn't sell.",
      tag("INVESTOR B"),
      chips(["Doesn't sell"])),
    S("Doesn't check the app.",
      tag("INVESTOR B"),
      chips(["Doesn't sell", "Doesn't check the app"])),
    S("Just waits.",
      tag("INVESTOR B"),
      chips(["Doesn't sell", "Doesn't check the app", "Just waits"])),
    Q(3.2, tag("AUGUST 2026"), head("Who has more today — and {a:how much}?", size=66),
      versus(("Investor A", "€?", 0, "amber", 0), ("Investor B", "€?", 0, "amber", 0)), pause(), timer(3)),
    S("Today, investor A has @a about eight thousand eight hundred euros.",
      tag("AUGUST 2026"),
      versus(("Investor A", "€{:,.0f}", 8813, "red", 5515), ("Investor B", "€?", 0, "slate", 0), at="a")),
    S("Less than they started with, twenty-seven years later.",
      tag("AUGUST 2026"),
      versus(("Investor A", "€{:,.0f}", 8813, "red", 8813), ("Investor B", "€?", 0, "slate", 0)),
      stamp("LESS THAN €10,000", angle=-6)),
    S("And investor B has @a forty-six thousand.",
      tag("AUGUST 2026"),
      versus(("Investor A", "€{:,.0f}", 8813, "red", 8813), ("Investor B", "€{:,.0f}", 46032, "green", 5515), at="a")),
    S("And here's the cruel part.",
      head("The {r:cruel} part.", size=120)),
    S("Investor A didn't feel stupid in 2003.",
      tag("INVESTOR A · 2003"),
      strike("STUPID", size=170)),
    S("They felt smart.",
      tag("INVESTOR A · 2003"),
      big("SMART", color="green", size=190)),
    S("They had avoided the pain.",
      tag("INVESTOR A · 2003"),
      head("They {g:avoided the pain}.")),
    S("Every bad headline for the next ten years told them they were right.",
      ticker([("“STOCKS ARE DEAD”", "red"), ("“LOST DECADE”", "red"), ("“CASH IS KING”", "amber"),
              ("“2008: WORST CRASH SINCE 1929”", "red")]),
      head("Every headline: {g:you were right}")),
    S("That's why panic selling is so dangerous.",
      stamp("DANGEROUS", size=120, angle=-6)),
    S("It feels like the responsible thing to do, @a and the bill only arrives many years later.",
      head("It feels {g:responsible}…"),
      sub("…the bill arrives {r:years later}.", at="a")),

    # ================================================================ CHAPTER 7
    S("Chapter seven. The number that matters.", *chapter(7)),
    S("Here it is. @a Thirty-seven thousand euros.",
      count(37219, "€{:,.0f}", color="amber", size=210, at="a")),
    S("That's the difference between investor A and investor B.",
      count(37219, "€{:,.0f}", color="amber", size=150, frm=37219),
      versus(("Investor A", "€{:,.0f}", 8813, "red", 8813), ("Investor B", "€{:,.0f}", 46032, "green", 46032))),
    S("Same money, same index, same start date, same crash.",
      chips(["Same money", "Same index", "Same start", "Same crash"])),
    S("The only difference was one decision, made in a moment of fear.",
      big("1 DECISION", color="amber", size=170),
      sub("made in a moment of {r:fear}")),
    S("That's the price of panic.",
      count(37219, "€{:,.0f}", color="red", size=200, frm=37219),
      stamp("THE PRICE OF PANIC", angle=-6)),
    S("No ETF, no equal weighting, no clever strategy came anywhere close to that number in this replay.",
      bars([("Panic vs patience", 37219, "€37,219", "red"), ("Best fund swap (scenario B)", 6.7 / 45.2 * 10000, "≈ €1,500", "slate")], maxv=40000),
      sub("on €10,000 · illustrative")),
    S("@a Your behaviour mattered more than your fund.",
      head("Your {a:behaviour} mattered more", at="a"),
      head("than your {a:fund}.", delay=0.6)),
    S("Let's recap what the euro data showed us.",
      tag("RECAP"),
      head("Recap", size=130)),
    S("Buying at the dot-com top: @a forty-five percent down, and thirteen years to get back to even.",
      tag("RECAP"), rows(RECAP[:1], at="a")),
    S("The dollar: @a it can add a second punch of up to forty percent, or soften the blow.",
      tag("RECAP"), rows(RECAP[:1]), rows(RECAP[1:2], at="a")),
    S("Swapping one stock index for another: @a helps in a tech-only correction, barely matters in a full crash.",
      tag("RECAP"), rows(RECAP[:2]), rows(RECAP[2:3], at="a")),
    S("A sixty forty with euro bonds: @a back to even eight years sooner, for a smaller final result.",
      tag("RECAP"), rows(RECAP[:3]), rows(RECAP[3:4], at="a")),
    S("The monthly saver: @a money multiplied by more than four. And panic selling: @b a thirty-seven thousand euro mistake.",
      tag("RECAP"), rows(RECAP[:4]), rows(RECAP[4:5], at="a"), rows(RECAP[5:], at="b")),
    S("And this isn't just my replay.",
      head("Not just {a:my} replay.")),
    S("Morningstar's yearly Mind the Gap study keeps finding the same thing: @a investors earn less than the funds they own, because they buy after the rises and sell after the falls.",
      tag("MORNINGSTAR · MIND THE GAP"),
      versus(("Funds earn", "{}", 0, "green", 0), ("Investors earn", "{}", 0, "red", 0), notes=("the full return", "less")),
      sub("Buy after rises · sell after falls", at="a")),
    S("So, is AI a bubble?",
      head("So… is AI a {a:bubble}?", size=110)),
    S("Honestly, I don't know.",
      stamp("I DON'T KNOW", color="amber", size=110, angle=-6)),
    S("And neither does anyone on YouTube who tells you they do.",
      stamp("I DON'T KNOW", color="amber", size=110, angle=-6),
      sub("…neither does {r:anyone on YouTube}")),
    S("And even if it is a bubble, that doesn't mean AI is fake.",
      head("A bubble ≠ {g:fake technology}")),
    S("The internet wasn't fake either.",
      head("The internet wasn't fake {a:either}.")),
    S("Amazon survived the dot-com crash and became one of the biggest companies on Earth.",
      tag("AMAZON"),
      big("SURVIVED", color="green", size=170)),
    S("But between 1999 and 2001, @a Amazon's share price still fell by more than ninety percent.",
      tag("AMAZON · 1999 → 2001"),
      count(-90, "{:.0f}%+", color="red", at="a")),
    S("Being right about the technology is not the same as being right about the price.",
      rows([("Right technology", "✓", "green"), ("Right price", "✕", "red")])),
    S("The E C B thinks a correction is likely.",
      pill("ECB"),
      head("A correction is {r:likely}.")),
    S("But bubbles can also run much longer than anyone expects.",
      head("Bubbles can run {a:much longer}.")),
    S("@a In 1996, Alan Greenspan warned about irrational exuberance.",
      tag("DECEMBER 1996"),
      head("“Irrational {a:exuberance}”", at="a")),
    S("The Nasdaq then almost quadrupled before it crashed.",
      tag("NASDAQ · 1996 → 2000"),
      count(4, "≈×{:.0f}", color="green", size=220),
      sub("…before it crashed")),
    S("What I do know is this: we have twenty-seven years of real euro data, two full bubbles, and the same lesson every single time.",
      chips(["27 years", "2 bubbles", "1 lesson"])),
    S("The crash itself never decided who ended up rich.",
      head("The crash {a:never decided}.")),
    S("@a What people did during the crash did.",
      head("{a:What people did} decided.", size=96, at="a")),
    S("So instead of predicting, here's what I'd check in my own portfolio.",
      tag("MY CHECKLIST · NOT ADVICE"),
      head("Check, don't {a:predict}.", size=110)),
    S("This is not financial advice, just a checklist.",
      tag("MY CHECKLIST · NOT ADVICE"),
      stamp("NOT ADVICE", color="amber", angle=-6)),
    S("One. Look at your ETF's top ten and its country weights. @a Know what you actually own.",
      tag("MY CHECKLIST · NOT ADVICE"), rows(CHECK[:1], at="a")),
    S("Two. Set your mix of stocks and bonds by when you need the money, not by the headlines.",
      tag("MY CHECKLIST · NOT ADVICE"), rows(CHECK[:1]), rows(CHECK[1:2], delay=0.3)),
    S("Three. If you diversify away from the giants, do it for the long run, knowing it can lag for a decade.",
      tag("MY CHECKLIST · NOT ADVICE"), rows(CHECK[:2]), rows(CHECK[2:3], delay=0.3)),
    S("Four. Automate your monthly plan, so a scary headline can't stop it.",
      tag("MY CHECKLIST · NOT ADVICE"), rows(CHECK[:3]), rows(CHECK[3:4], delay=0.3)),
    S("And five. Write down today what you will do if your portfolio drops forty percent.",
      tag("MY CHECKLIST · NOT ADVICE"), rows(CHECK[:4]), rows(CHECK[4:], delay=0.5)),
    S("Decide now, while you're calm.",
      tag("MY CHECKLIST · NOT ADVICE"), rows(CHECK),
      stamp("DECIDE NOW", color="green", angle=-6)),
    S("Question three.",
      tag("QUESTION 3/3", color="amber"),
      head("Question {a:three}.", size=110)),
    S("And be honest.",
      pill("BE HONEST")),
    S("If your portfolio dropped forty-five percent next year, what would you do?",
      tag("QUESTION 3/3", color="amber"),
      head("Your portfolio drops {r:45%}. You…", size=70),
      options(["SELL", "STOP BUYING", "KEEP GOING"], countdown=False)),
    S("A, sell. B, stop buying. Or C, keep going. @a Tell me in the comments.",
      pill("BE HONEST"),
      head("What would {a:you} do?"),
      boxes(["A", "B", "C"], at="a")),
    Q(2.0, pill("BE HONEST"), head("What would {a:you} do?"), boxes(["A", "B", "C"]), pause("COMMENT BELOW")),
    S("If you want to see how a crash right before retirement changes everything, watch my video where I simulated ten thousand European retirements. @a It's on my channel.",
      card("FULL VIDEO", "The 4% Rule in Europe: I Simulated 10,000 Retirements")),
    S("And if you want more real euro data instead of hype, subscribe.",
      head("Real euro data. {a:No hype.}"),
      subscribe()),
    S("Every video on this channel is built on numbers you can check.",
      head("Numbers you can {a:check}."),
      subscribe()),
    S("Thanks for watching. See you in the next one.",
      head("THE AI BUBBLE {a:IN EUROPE}", size=100),
      sub("Data, not hype. · {a:EuroindexLab}"),
      src="Not financial advice. Past performance does not guarantee future results."),
]

CHAPTER_STARTS = [i for i, s in enumerate(SEGMENTS) if s["text"].startswith("Chapter ")]
